import type { Meta } from '@storybook/nextjs';
import type ValuePicker from '../ValuePicker';
export const valuePickerArgTypes: Meta<typeof ValuePicker>['argTypes'] = {
  variant: {
    description: 'Which sub-component renders. Drives the whole shape of the control.',
    control: 'select',
    options: ['amount', 'value', 'paired', 'stacked-paired', 'date', 'date-range'],
    table: { category: 'Variant', defaultValue: { summary: 'amount' } },
  },
  value: { description: 'The current value. Controlled — pair with `onChange`.', table: { category: 'Value' } },
  onChange: { description: 'Receives the new value as a string, already clamped to min/max.', table: { category: 'Value' } },
  min: { control: 'number', table: { category: 'Value' } },
  max: { control: 'number', table: { category: 'Value' } },
  defaultStep: { description: 'Step for the +/- buttons. Defaults to 500 (0.5 for decimals).', table: { category: 'Value' } },
  allowDecimals: { description: 'Forces fractional input.', control: 'boolean', table: { category: 'Value' } },
  placeholder: { control: 'text', table: { category: 'Value' } },
  title: { description: 'Heading text.', table: { category: 'Label' } },
  titleStyle: {
    description: '`merged` fuses title to card top; `default` puts it above.',
    control: 'inline-radio',
    options: ['merged', 'default'],
    table: { category: 'Label', defaultValue: { summary: 'merged' } },
  },
  showWords: { description: 'Renders amount in words below the card.', control: 'boolean', table: { category: 'Label' } },
  locale: { description: 'Number formatting locale.', control: 'text', table: { category: 'Label' } },
  symbol: { description: 'Prefix badge content.', control: 'text', table: { category: 'Symbol', defaultValue: { summary: '₹' } } },
  symbolPosition: { control: 'inline-radio', options: ['left', 'right'], table: { category: 'Symbol', defaultValue: { summary: 'left' } } },
  symbolBg: { control: 'boolean', table: { category: 'Symbol', defaultValue: { summary: 'true' } } },
  endAdornment: { description: 'Slots extra control between field and buttons.', table: { category: 'Symbol' } },
  stepData: { description: 'Quick-step buttons array.', table: { category: 'Steps' } },
  stepRows: { description: 'Multi-row step grid.', table: { category: 'Steps' } },
  singleRow: { description: 'Flattens steps into one row.', control: 'boolean', table: { category: 'Steps' } },
  tabs: { description: 'Tab strip above the input.', table: { category: 'Tabs' } },
  activeTab: { table: { category: 'Tabs' } },
  defaultTab: { table: { category: 'Tabs' } },
  onTabChange: { table: { category: 'Tabs' } },
  tabSize: { control: 'inline-radio', options: ['xs', 'sm', 'md', 'lg', 'xl'], table: { category: 'Tabs', defaultValue: { summary: 'md' } } },
  scale: {
    description: 'Sizing mode.',
    control: 'inline-radio',
    options: ['auto', 'container', 'mobile', 'desktop'],
    table: { category: 'Chrome', defaultValue: { summary: 'auto' } },
  },
  compact: { control: 'boolean', table: { category: 'Chrome' } },
  embedded: { control: 'boolean', table: { category: 'Chrome' } },
  disabled: { control: 'boolean', table: { category: 'Chrome' } },
  readOnly: { control: 'boolean', table: { category: 'Chrome' } },
  sourceBadgeText: { table: { category: 'Paired slots' } },
  targetBadgeText: { table: { category: 'Paired slots' } },
  sourceSlot: { table: { category: 'Paired slots' } },
  targetSlot: { table: { category: 'Paired slots' } },
  sourceOptions: { table: { category: 'Paired slots' } },
  targetOptions: { table: { category: 'Paired slots' } },
  sourceValue: { table: { category: 'Paired slots' } },
  targetValue: { table: { category: 'Paired slots' } },
  onSourceChange: { table: { category: 'Paired slots' } },
  onTargetChange: { table: { category: 'Paired slots' } },
  dateMode: { control: 'inline-radio', options: ['date', 'year'], table: { category: 'Date range', defaultValue: { summary: 'date' } } },
  startTitle: { control: 'text', table: { category: 'Date range', defaultValue: { summary: 'Start' } } },
  endTitle: { control: 'text', table: { category: 'Date range', defaultValue: { summary: 'End' } } },
  startDate: { table: { category: 'Date range' } },
  endDate: { table: { category: 'Date range' } },
  setStartDate: { table: { category: 'Date range' } },
  setEndDate: { table: { category: 'Date range' } },
  startMinDate: { control: 'text', table: { category: 'Date range' } },
  startYearOptions: { table: { category: 'Date range' } },
  endYearOptions: { table: { category: 'Date range' } },
};
