import type { ShiprocketAccountData, ShiprocketOrder } from './types';
export interface ShiprocketCreateTabProps {
  account: ShiprocketAccountData | null;
  orders: ShiprocketOrder[];
  pickupLoc: string;
  paymentMode: 'Prepaid' | 'COD';
  custName: string;
  custPhone: string;
  custEmail: string;
  custAddress: string;
  custAddress2: string;
  custPincode: string;
  custCity: string;
  custState: string;
  pincodeLoading: boolean;
  weight: string;
  length: string;
  breadth: string;
  height: string;
  itemName: string;
  itemSku: string;
  itemQty: string;
  itemPrice: string;
  volumetricWeight: string;
  appliedWeight: string;
  creatingOrder: boolean;
  createdOrderResult: { orderId: number; shipmentId: number } | null;
  onSubmit: (e: React.FormEvent) => void;
  onCancel: () => void;
  onOpenShipModal: (order: ShiprocketOrder) => void;
  onPrintLabel: (shipmentId: number) => void;
  onPickupLocChange: (val: string) => void;
  onPaymentModeChange: (val: 'Prepaid' | 'COD') => void;
  onCustNameChange: (val: string) => void;
  onCustPhoneChange: (val: string) => void;
  onCustEmailChange: (val: string) => void;
  onCustAddressChange: (val: string) => void;
  onCustAddress2Change: (val: string) => void;
  onCustPincodeChange: (val: string) => void;
  onCustCityChange: (val: string) => void;
  onCustStateChange: (val: string) => void;
  onWeightChange: (val: string) => void;
  onLengthChange: (val: string) => void;
  onBreadthChange: (val: string) => void;
  onHeightChange: (val: string) => void;
  onItemNameChange: (val: string) => void;
  onItemSkuChange: (val: string) => void;
  onItemQtyChange: (val: string) => void;
  onItemPriceChange: (val: string) => void;
}
