export const NAV_TITLES: Record<string, string> = {
  '/': 'Rupee Calculator',
  '/temp-value-picker': 'ValuePicker Preview',
  '/demo/value-picker': 'ValuePicker Preview',
  '/login': 'Sign In',
  '/admin': 'Data administration',
  '/admin/shiprocket-rates': 'Shiprocket Rates',
  '/admin/volumetric-weight': 'Volumetric Weight',
  '/admin/wood-calculator': 'Wood Calculator',
  '/admin/quick-notes': 'Quick Notes',
  '/utilities/quick-notes': 'Quick Notes',
  '/admin/notes': 'Quick Notes',
  '/notes': 'Quick Notes',
  '/about': 'About',
  '/privacy': 'Privacy Policy',
  '/disclaimer': 'Disclaimer',
  '/emi': 'EMI Calculator',
  '/emi-calculator': 'EMI Calculator',
  '/deposits/fd': 'Fixed Deposits',
  '/fd-calculator': 'Fixed Deposits',
  '/deposits/rd': 'Recurring Deposits',
  '/rd-calculator': 'Recurring Deposits',
  '/compound-interest-calculator': 'Compound Interest',
  '/economics/inflation-rates': 'Inflation Rates',
  '/inflation-calculator': 'Inflation Rates',
  '/economics/ppp-exchange-rate': 'PPP Exchange Rate',
  '/ppp-calculator': 'PPP Exchange Rate',
  '/currency-converter': 'Currency Converter',
  '/utilities/currency-converter': 'Currency Converter',
  '/economics/currency-converter': 'Currency Converter',
  '/fixed-plans/fixed-rate-sip': 'Fixed Rate SIP',
  '/sip-calculator': 'SIP Calculator',
  '/fixed-plans/fixed-rate-swp': 'Fixed Rate SWP',
  '/swp-calculator': 'SWP Calculator',
  '/mutual-funds/lumpsum': 'Lumpsum',
  '/mutual-funds/sip': 'SIP',
  '/mutual-funds/swp': 'SWP',
  '/calculator': 'Calculator',
  '/utilities/calculator': 'Calculator',
  '/date-calculator': 'Date Calculator',
  '/utilities/date-calculator': 'Date Calculator',
  '/utilities/unit-converter': 'Unit Converter',
  '/ppf-calculator': 'PPF Calculator',
  '/deposits/ppf': 'PPF Calculator',
  '/fixed-plans/ppf': 'PPF Calculator',
  '/nps-calculator': 'NPS Calculator',
  '/fixed-plans/nps': 'NPS Calculator',
  '/income-tax-calculator': 'Income Tax Calculator',
  '/tax-calculator': 'Income Tax Calculator',
  '/tax/income-tax': 'Income Tax Calculator',
  '/file-itr': 'Upload Form 16 & File ITR',
  '/file-income-tax-return': 'Upload Form 16 & File ITR',
};
export const getNavTitle = (pathname: string): string => {
  return NAV_TITLES[pathname] ?? 'Rupee Calculator';
};
