export interface ThemedWordSet {
  theme: string;
  words: string[];
}
export const THEMED_WORD_SETS: ThemedWordSet[] = [
  {
    theme: 'Optics & Visuals',
    words: [
      'LENS', 'BEAM', 'GLOW', 'ZOOM', 'VIEW', 'IRIS', 'SCAN', 'TINT',
      'OPTIC', 'FOCUS', 'PRISM', 'LASER', 'LIGHT', 'SHINE', 'SIGHT', 'FLASH', 'PHOTO', 'CLEAR', 'IMAGE',
      'CAMERA', 'MIRROR', 'VISION', 'PHOTON', 'SHADOW', 'FILTER', 'SENSOR', 'SCREEN', 'VECTOR', 'OPTICS',
      'PICTURE', 'REFLECT', 'DISPLAY', 'SHUTTER', 'VISIBLE', 'OPTICAL',
      'GRAPHICS', 'APERTURE', 'SPECTRUM', 'EXPOSURE', 'ILLUSION', 'SUNLIGHT', 'INFRARED',
      'CINEMATIC', 'TELESCOPE', 'PANORAMIC', 'ANIMATION', 'RENDERING',
      'MICROSCOPE', 'REFLECTING', 'ILLUMINATE', 'PROJECTION', 'RESOLUTION', 'HOLOGRAPHY',
      'PHOTOGRAPHY', 'TRANSPARENT',
      'ILLUMINATION', 'SPECTROMETER',
      'CONTRAST', 'DIFFRACT', 'LUMINOUS', 'PIGMENTS', 'RADIANCE', 'VIBRANCE', 'BINOCULAR', 'HIGHLIGHT', 'LUMINANCE', 'MAGNIFIER', 'PERISCOPE', 'POLARIZED', 'POLARIZER', 'PROJECTOR', 'SPOTLIGHT', 'ABERRATION', 'BRIGHTNESS', 'IRIDESCENT', 'MONOCHROME', 'OPHTHALMIC', 'REFRACTION', 'SATURATION', 'SILHOUETTE', 'VIEWFINDER', 'FLUORESCENT', 'STEREOSCOPE', 'KALEIDOSCOPE', 'LUMINESCENCE', 'PHOTOGRAPHER',
      'HALO', 'BLINK', 'COLOR', 'GLARE', 'VIVID', 'BRIGHT', 'LUSTER', 'GLIMMER', 'GLITTER', 'LANTERN', 'SHIMMER', 'SPARKLE', 'TWINKLE',
    ],
  },
  {
    theme: 'Tech & Computing',
    words: [
      'BYTE', 'CODE', 'DATA', 'NODE', 'FLOW', 'CHIP', 'DISK', 'WIRE', 'HOST', 'LINK', 'PORT',
      'LOGIC', 'ROUTE', 'STACK', 'ARRAY', 'QUEUE', 'GRAPH', 'TABLE', 'QUERY', 'FETCH', 'PATCH', 'BUILD', 'CYBER', 'RADAR', 'PIXEL',
      'SERVER', 'ROUTER', 'CODING', 'SCRIPT', 'BINARY', 'BUFFER', 'MEMORY', 'CLIENT', 'ENGINE', 'SOCKET', 'PACKET', 'SIGNAL', 'MATRIX',
      'PROGRAM', 'NETWORK', 'STORAGE', 'CIRCUIT', 'PROCESS', 'DESKTOP', 'POINTER', 'CONSOLE', 'COMPUTE', 'BROWSER', 'GATEWAY', 'RUNTIME', 'PACKAGE', 'SCANNER', 'DIGITAL', 'VIRTUAL',
      'DATABASE', 'SOFTWARE', 'HARDWARE', 'TERMINAL', 'INTERNET', 'FIREWALL', 'PROTOCOL', 'WIRELESS', 'FIRMWARE', 'BACKBONE', 'FUNCTION', 'VARIABLE', 'COMPILER', 'DEBUGGER', 'KEYBOARD',
      'ALGORITHM', 'PROCESSOR', 'INTERFACE', 'FRAMEWORK', 'COMPONENT', 'DEVELOPER', 'EXECUTION', 'BANDWIDTH', 'DIRECTORY', 'MAINFRAME',
      'CYBERSPACE', 'CONTROLLER', 'PROGRAMMER', 'SIMULATION', 'ENCRYPTION', 'TECHNOLOGY',
      'PROGRAMMING', 'APPLICATION', 'WORKSTATION', 'ELECTRONICS', 'MOTHERBOARD',
      'CRYPTOGRAPHY', 'ARCHITECTURE', 'TRANSMISSION',
      'DOWNLOAD', 'BENCHMARK', 'BLUETOOTH', 'ENCRYPTED', 'MICROCHIP', 'AUTOMATION', 'BOOTLOADER', 'CALCULATOR', 'DEPLOYMENT', 'MULTIMEDIA', 'PERIPHERAL', 'REPOSITORY', 'SMARTPHONE', 'TRANSISTOR', 'COMPUTATION', 'DISTRIBUTED', 'INTEGRATION', 'SPREADSHEET', 'SYNCHRONIZE', 'CONNECTIVITY', 'INSTALLATION', 'MICROSERVICE', 'MULTITASKING', 'OPTIMIZATION',
    ],
  },
  {
    theme: 'Space & Cosmos',
    words: [
      'STAR', 'MOON', 'DUST', 'NOVA', 'MARS', 'SUNS',
      'ORBIT', 'COMET', 'SOLAR', 'SPACE', 'VENUS', 'PLUTO',
      'PLANET', 'GALAXY', 'NEBULA', 'COSMOS', 'ROCKET', 'PULSAR', 'METEOR', 'AURORA',
      'ECLIPSE', 'GRAVITY', 'JUPITER', 'MERCURY', 'ORBITAL', 'SHUTTLE',
      'ASTEROID', 'UNIVERSE', 'STARDUST', 'DEEPVOID', 'SPACEMAN',
      'TELESCOPE', 'ASTRONOMY', 'SATELLITE', 'SUPERNOVA', 'SPACECRAFT', 'COSMOLOGY',
      'ATMOSPHERE', 'ASTRONOMER', 'INTERSTELL', 'COSMONAUTS',
      'CONSTELLATE', 'OBSERVATORY', 'ASTROPHYSIC',
      'ASTROPHYSICS', 'SUPERCLUSTER', 'INTERGALACTIC',
      'GALACTIC', 'MAGNETAR', 'MOONBEAM', 'ASTEROIDS', 'ASTRONAUT', 'CELESTIAL', 'COSMONAUT', 'EXOPLANET', 'LAUNCHPAD', 'METEORITE', 'MOONLIGHT', 'SPACESHIP', 'STARLIGHT', 'HEMISPHERE', 'PROPULSION', 'TELESCOPIC', 'TRAJECTORY', 'GRAVITATION', 'PLANETARIUM', 'ASTRONOMICAL', 'COSMOLOGICAL', 'INTERSTELLAR', 'SPECTROSCOPY',
      'HALO', 'LUNA', 'RING', 'VOID', 'ALIEN', 'LUNAR', 'ORION', 'PROBE', 'STARS', 'TITAN', 'COMETS', 'LAUNCH', 'ORBITS', 'QUASAR', 'SATURN', 'URANUS', 'EQUINOX', 'NEPTUNE', 'ROCKETS', 'STARLIT',
    ],
  },
  {
    theme: 'Nature & Earth',
    words: [
      'RAIN', 'WIND', 'PEAK', 'ROCK', 'SOIL', 'LEAF', 'SEED', 'TREE', 'WOOD', 'PARK', 'LAKE', 'POND', 'SNOW', 'MIST',
      'RIVER', 'OCEAN', 'EARTH', 'STONE', 'PLANT', 'WATER', 'CLOUD', 'STORM', 'FLORA', 'FAUNA', 'BEACH', 'CLIFF', 'OASIS', 'DUNES', 'CORAL', 'REEFS', 'FIELD', 'GRASS', 'ROOTS', 'BLOOM', 'GROVE', 'FROST',
      'FOREST', 'CANYON', 'VALLEY', 'MEADOW', 'ISLAND', 'STREAM', 'SPRING', 'AUTUMN', 'WINTER', 'SUMMER', 'BREEZE', 'SUNSET', 'NATURE', 'DESERT', 'JUNGLE', 'TROPIC', 'BRANCH', 'FLOWER', 'TIMBER',
      'GLACIER', 'VOLCANO', 'WEATHER', 'HORIZON', 'CASCADE', 'NATURAL', 'RAINBOW', 'TSUNAMI', 'MONSOON', 'TORNADO', 'CURRENT', 'ICEBERG', 'HABITAT',
      'MOUNTAIN', 'WILDLIFE', 'SUNSHINE', 'FORESTRY', 'WOODLAND', 'SEASHORE', 'BLIZZARD', 'RAINDROP', 'OVERCAST', 'WILDWOOD',
      'LANDSCAPE', 'BIOSPHERE', 'MOUNTAINS', 'WATERFALL', 'EVERGREEN', 'LIGHTNING',
      'WILDERNESS', 'WATERFALLS', 'LANDSCAPES', 'RAINSTORMS', 'RAINFOREST', 'CLEARWATER',
      'ENVIRONMENT', 'TEMPERATURE', 'SPECTACULAR',
      'BIODIVERSITY', 'CONSERVATION',
      'MEADOWS', 'WETLANDS', 'COASTLINE', 'ECOSYSTEM', 'GRASSLAND', 'HURRICANE', 'VOLCANOES', 'BLOSSOMING', 'SUNFLOWERS', 'WILDFLOWER', 'COUNTRYSIDE', 'GROUNDWATER', 'HIBERNATION', 'MOUNTAINTOP', 'UNDERGROWTH', 'WATERCOURSE', 'MOUNTAINSIDE', 'THUNDERCLOUD', 'THUNDERSTORM',
    ],
  },
  {
    theme: 'Animals & Wildlife',
    words: [
      'BEAR', 'WOLF', 'FISH', 'BIRD', 'LION', 'DEER', 'DUCK', 'FROG', 'HAWK', 'CRAB', 'SWAN',
      'TIGER', 'WHALE', 'SHARK', 'EAGLE', 'OTTER', 'MOOSE', 'ZEBRA', 'HORSE', 'SHEEP', 'PANDA', 'KOALA',
      'FALCON', 'SALMON', 'BEAVER', 'MONKEY', 'BADGER', 'JAGUAR', 'PARROT', 'TURTLE', 'LIZARD',
      'DOLPHIN', 'CHEETAH', 'PENGUIN', 'LEOPARD', 'PELICAN', 'PANTHER', 'BUFFALO', 'SPARROW', 'GIRAFFE', 'GORILLA', 'OSTRICH', 'HAMSTER',
      'ELEPHANT', 'KANGAROO', 'ANTELOPE', 'HEDGEHOG', 'REINDEER', 'PLATYPUS', 'SQUIRREL', 'FLAMINGO',
      'ALLIGATOR', 'CHAMELEON', 'PORCUPINE', 'CROCODILE',
      'CARNIVORES', 'HERBIVORES', 'VERTEBRATE',
      'CRUSTACEANS', 'SALAMANDERS',
      'CHIPMUNK', 'MONGOOSE', 'PARAKEET', 'SEAHORSE', 'STARFISH', 'TORTOISE', 'ARMADILLO', 'BARRACUDA', 'BUMBLEBEE', 'BUTTERFLY', 'DRAGONFLY', 'GREYHOUND', 'JELLYFISH', 'ORANGUTAN', 'TARANTULA', 'WOLVERINE', 'BLOODHOUND', 'CHIMPANZEE', 'CHINCHILLA', 'KINGFISHER', 'RHINOCEROS', 'ROADRUNNER', 'SALAMANDER', 'WOODPECKER', 'CATERPILLAR', 'GRASSHOPPER', 'HUMMINGBIRD', 'MOCKINGBIRD', 'NIGHTINGALE', 'RATTLESNAKE', 'BRONTOSAURUS', 'CATERPILLARS', 'GRASSHOPPERS', 'HIPPOPOTAMUS', 'RATTLESNAKES',
    ],
  },
  {
    theme: 'Science & Chemistry',
    words: [
      'ATOM', 'CELL', 'GENE', 'HEAT', 'ACID', 'MASS', 'BOND',
      'LASER', 'LIGHT', 'SOUND', 'BRAIN', 'HEART', 'PULSE', 'FORCE', 'POWER', 'SCALE',
      'ENERGY', 'FUSION', 'MAGNET', 'OXYGEN', 'PHOTON', 'SYSTEM', 'MATRIX', 'SENSOR', 'VOLUME',
      'ELEMENT', 'NEUTRON', 'QUANTUM', 'CRYSTAL', 'DIAMOND', 'PROTONS', 'ISOTOPE',
      'COMPOUND', 'ORGANISM', 'ELECTRON', 'MOLECULE', 'GENETICS', 'CATALYST', 'CELLULAR',
      'RESONANCE', 'STRUCTURE', 'EVOLUTION', 'DISCOVERY', 'PARTICLES', 'SYNTHESIS',
      'EXPERIMENT', 'LABORATORY', 'BIOLOGICAL', 'SCIENTIFIC', 'GEOPHYSICS',
      'MEASUREMENT', 'INTEGRATION', 'ACCELERATOR', 'BIOPHYSICAL',
      'EXPERIMENTAL', 'ACCELERATION', 'SUPERCONDUCT',
      'CHLORINE', 'ELEMENTS', 'HYDROGEN', 'NITROGEN', 'PERIODIC', 'REACTION', 'SOLUTION', 'TITANIUM', 'CHEMISTRY', 'MAGNESIUM', 'MOLECULAR', 'OXIDATION', 'POTASSIUM', 'TITRATION', 'CENTRIFUGE', 'HYPOTHESIS', 'PHOSPHORUS', 'CRYSTALLINE', 'ELECTROLYTE', 'EQUILIBRIUM', 'EVAPORATION', 'MICROSCOPIC', 'RADIOACTIVE', 'THERMOMETER', 'BIOCHEMISTRY', 'CONDUCTIVITY', 'DISTILLATION', 'FERMENTATION', 'SPECTROSCOPE',
      'IONS', 'LENS', 'SALT', 'ALLOY', 'ARGON', 'BORON', 'CARBON', 'ENZYME', 'PLASMA', 'NUCLEUS', 'POLYMER', 'PROTEIN',
    ],
  },
];
export const GENERAL_WORDS_BY_LENGTH: Record<number, string[]> = {
  4: [
    'STAR', 'MOON', 'CODE', 'BYTE', 'RAIN', 'WIND', 'ATOM', 'CELL', 'GENE',
    'LENS', 'BEAR', 'WOLF', 'FISH', 'BIRD', 'DATA', 'NODE', 'FLOW', 'PATH',
    'WAVE', 'PEAK', 'ROCK', 'SOIL', 'LEAF', 'SEED', 'ROSE', 'PINE', 'SAND',
    'GOLD', 'IRON', 'LION', 'DEER', 'DUCK', 'FROG', 'HAWK', 'CRAB', 'SWAN',
    'TREE', 'WOOD', 'PARK', 'LAKE', 'POND', 'SURF', 'TIDE', 'FIRE', 'HEAT',
    'COAL', 'DUST', 'MIST', 'SNOW', 'HAIL', 'CALM', 'WILD', 'CAMP', 'HIKE',
    'SHIP', 'SAIL', 'DOCK', 'PORT', 'ROAD', 'LANE', 'GRID', 'CHIP', 'DISC',
    'DISK', 'WIRE', 'PLUG', 'HOST', 'LINK', 'PAGE', 'FORM', 'ICON', 'FONT',
    'MENU', 'VIEW', 'SITE', 'CHAT', 'TEAM', 'USER', 'PLAN', 'TASK', 'TEST',
    'LOCK', 'KEYS', 'TIME', 'DATE', 'YEAR', 'NOON', 'DAWN', 'DUSK',
  ],
  5: [
    'OPTIC', 'FOCUS', 'PRISM', 'LASER', 'LOGIC', 'ORBIT', 'COMET', 'RIVER',
    'OCEAN', 'EARTH', 'SOLAR', 'TIGER', 'WHALE', 'BRAIN', 'HEART', 'LIGHT',
    'SHINE', 'SPACE', 'CLOUD', 'STORM', 'STONE', 'PLANT', 'WATER', 'SOUND',
    'SHARK', 'EAGLE', 'OTTER', 'MOOSE', 'ZEBRA', 'HORSE', 'SHEEP', 'PANDA',
    'KOALA', 'FLORA', 'FAUNA', 'BEACH', 'CLIFF', 'OASIS', 'DUNES', 'CORAL',
    'REEFS', 'FIELD', 'GRASS', 'ROOTS', 'SEEDS', 'BLOOM', 'TREES', 'WOODS',
    'GROVE', 'FROST', 'STEAM', 'SPARK', 'FLASH', 'PULSE', 'RADAR', 'FIBER',
    'PIXEL', 'MODEM', 'ROUTE', 'DRIVE', 'STACK', 'ARRAY', 'QUEUE', 'GRAPH',
    'TABLE', 'QUERY', 'FETCH', 'PATCH', 'BUILD', 'SCALE', 'SPEED', 'POWER',
    'FORCE', 'SMART', 'ROBOT', 'CYBER', 'TRACK', 'GUIDE', 'ATLAS', 'GLOBE',
  ],
  6: [
    'CAMERA', 'MIRROR', 'SERVER', 'ROUTER', 'PLANET', 'GALAXY', 'NEBULA',
    'COSMOS', 'ROCKET', 'FOREST', 'CANYON', 'VALLEY', 'MEADOW', 'ISLAND',
    'STREAM', 'FALCON', 'SALMON', 'ENERGY', 'FUSION', 'MAGNET', 'OXYGEN',
    'VISION', 'PHOTON', 'PENCIL', 'CANVAS', 'DESIGN', 'SHADOW', 'VECTOR',
    'SYSTEM', 'MODULE', 'CODING', 'SCRIPT', 'BINARY', 'BUFFER', 'MEMORY',
    'CLIENT', 'ENGINE', 'THREAD', 'SOCKET', 'BRIDGE', 'PACKET', 'SIGNAL',
    'SENSOR', 'MATRIX', 'LAPTOP', 'SCREEN', 'DEVICE', 'VOLUME', 'SPRING',
    'AUTUMN', 'WINTER', 'SUMMER', 'BREEZE', 'CLOUDS', 'SUNSET', 'NATURE',
    'DESERT', 'JUNGLE', 'TROPIC', 'BRANCH', 'FLOWER', 'TIMBER', 'BEAVER',
    'MONKEY', 'BADGER', 'JAGUAR', 'PARROT', 'TURTLE', 'LIZARD',
  ],
  7: [
    'PICTURE', 'REFLECT', 'PROGRAM', 'NETWORK', 'STORAGE', 'CIRCUIT', 'PROCESS',
    'ECLIPSE', 'GRAVITY', 'GLACIER', 'VOLCANO', 'WEATHER', 'HORIZON', 'CASCADE',
    'DOLPHIN', 'CHEETAH', 'PENGUIN', 'LEOPARD', 'PELICAN', 'PANTHER', 'BUFFALO',
    'ELEMENT', 'NEUTRON', 'QUANTUM', 'CRYSTAL', 'DIAMOND', 'HARMONY', 'DESKTOP',
    'POINTER', 'CONSOLE', 'COMPUTE', 'BROWSER', 'GATEWAY', 'ROUTING', 'ADAPTER',
    'COMPILE', 'RUNTIME', 'PACKAGE', 'ARCHIVE', 'SCANNER', 'MACHINE', 'DIGITAL',
    'VIRTUAL', 'DYNAMIC', 'NATURAL', 'RAINBOW', 'TSUNAMI', 'MONSOON', 'TORNADO',
    'CURRENT', 'ICEBERG', 'HABITAT', 'SPARROW', 'GIRAFFE', 'GORILLA', 'OSTRICH',
    'HAMSTER',
  ],
  8: [
    'GRAPHICS', 'APERTURE', 'DATABASE', 'SOFTWARE', 'HARDWARE', 'TERMINAL',
    'ASTEROID', 'MOUNTAIN', 'WILDLIFE', 'SUNSHINE', 'ELEPHANT', 'KANGAROO',
    'COMPOUND', 'ORGANISM', 'ELECTRON', 'MOLECULE', 'GENETICS', 'CATALYST',
    'SPECTRUM', 'UNIVERSE', 'SYMPHONY', 'HORIZONS', 'ILLUSION', 'CREATION',
    'PLATFORM', 'INTERNET', 'FIREWALL', 'PROTOCOL', 'WIRELESS', 'CELLULAR',
    'FIRMWARE', 'BACKBONE', 'SYMBOLIC', 'FUNCTION', 'VARIABLE', 'COMPILER',
    'DEBUGGER', 'FORESTRY', 'WOODLAND', 'SEASHORE', 'BLIZZARD', 'RAINDROP',
    'OVERCAST', 'WILDWOOD', 'ANTELOPE', 'HEDGEHOG', 'REINDEER', 'PLATYPUS',
    'SQUIRREL', 'KEYBOARD', 'FLAMINGO', 'SUNLIGHT',
  ],
  9: [
    'CINEMATIC', 'ALGORITHM', 'TELESCOPE', 'ASTRONOMY', 'SATELLITE', 'SUPERNOVA',
    'LANDSCAPE', 'RESONANCE', 'EXPLORING', 'BIOSPHERE', 'ADVENTURE', 'STRUCTURE',
    'EVOLUTION', 'DISCOVERY', 'BRILLIANT', 'KNOWLEDGE', 'MOUNTAINS', 'COMPUTING',
    'PROCESSOR', 'INTERFACE', 'FRAMEWORK', 'COMPONENT', 'DEVELOPER', 'EXECUTION',
    'BANDWIDTH', 'ANIMATION', 'RENDERING', 'DIRECTORY', 'OPERATION', 'MAINFRAME',
    'WATERFALL', 'EVERGREEN', 'LIGHTNING', 'ALLIGATOR', 'CHAMELEON', 'PORCUPINE',
    'CROCODILE',
  ],
  10: [
    'MICROSCOPE', 'REFLECTING', 'CONNECTION', 'INNOVATION', 'ATMOSPHERE',
    'NAVIGATION', 'GENERATION', 'EXPEDITION', 'EXPERIMENT', 'LABORATORY',
    'POPULATION', 'TECHNOLOGY', 'ILLUMINATE', 'PROJECTION', 'CYBERSPACE',
    'CONTROLLER', 'PROGRAMMER', 'SIMULATION', 'ENCRYPTION', 'PRODUCTION',
    'BIOLOGICAL', 'SCIENTIFIC', 'GEOPHYSICS', 'ASTRONOMER', 'SPACECRAFT',
    'WILDERNESS', 'WATERFALLS', 'LANDSCAPES', 'RAINSTORMS', 'RAINFOREST',
    'CLEARWATER',
  ],
  11: [
    'PHOTOGRAPHY', 'CALCULATION', 'EXPLORATION', 'OBSERVATION', 'DEVELOPMENT',
    'MEASUREMENT', 'INTERACTION', 'INTEGRATION', 'CONSTELLATE', 'SPECTACULAR',
    'OBSERVATORY', 'PROGRAMMING', 'APPLICATION', 'ENVIRONMENT', 'ACCELERATOR',
    'TEMPERATURE', 'WORKSTATION', 'ELECTRONICS', 'INTERFACING', 'BIOPHYSICAL',
    'MOTHERBOARD',
  ],
  12: [
    'ILLUMINATION', 'ACCELERATION', 'BIODIVERSITY', 'TECHNOLOGIES', 'ASTROPHYSICS',
    'EXPERIMENTAL', 'APPRECIATION', 'ARCHITECTURE', 'TRANSMISSION', 'SUPERCLUSTER',
    'CRYPTOGRAPHY', 'COMPILATIONS', 'SUPERCONDUCT',
  ],
};
const ALL_WORDS_ARRAY: string[] = [
  ...Object.values(GENERAL_WORDS_BY_LENGTH).flat(),
  ...THEMED_WORD_SETS.flatMap((s) => s.words),
];
export const VALID_WORDS_SET = new Set<string>(
  ALL_WORDS_ARRAY.map((w) => w.toUpperCase())
);
export const getWordsOfLength = (
  length: number,
  theme?: string,
  excludeWords?: Set<string>
): string[] => {
  if (theme) {
    const set = THEMED_WORD_SETS.find(
      (s) => s.theme.toLowerCase() === theme.toLowerCase()
    );
    if (set) {
      let filtered = set.words.filter((w) => w.length === length);
      if (excludeWords) {
        filtered = filtered.filter((w) => !excludeWords.has(w));
      }
      return filtered;
    }
    return [];
  }
  const pool = GENERAL_WORDS_BY_LENGTH[length] ?? [];
  const valid = pool.filter((w) => w.length === length);
  if (excludeWords && excludeWords.size > 0) {
    const withoutExcluded = valid.filter((w) => !excludeWords.has(w));
    if (withoutExcluded.length > 0) return withoutExcluded;
  }
  return valid;
};
