const CURRENCY_CODES = [
  { name: "AFGHANISTAN", currency_name: "AFN", currency_code: "tk-AF" },
  { name: "ALBANIA", currency_name: "ALL", currency_code: "sq-AL" },
  { name: "ALGERIA", currency_name: "DZD", currency_code: "ar-DZ" },
  { name: "AMERICAN SAMOA", currency_name: "USD", currency_code: "en-US" },
  { name: "ANDORRA", currency_name: "EUR", currency_code: "ca-AD" },
  { name: "ANGOLA", currency_name: "AOA", currency_code: "pt-AO" },
  { name: "ANGUILLA", currency_name: "XCD", currency_code: "en-AI" },
  { name: "ANTARCTICA", currency_name: "", currency_code: "en-AQ" },
  { name: "ANTIGUA AND BARBUDA", currency_name: "XCD", currency_code: "en-AG" },
  { name: "ARGENTINA", currency_name: "ARS", currency_code: "es-AR" },
  { name: "ARMENIA", currency_name: "AMD", currency_code: "hy-AM" },
  { name: "ARUBA", currency_name: "AWG", currency_code: "nl-AW" },
  { name: "AUSTRALIA", currency_name: "AUD", currency_code: "en-AU" },
  { name: "AUSTRIA", currency_name: "EUR", currency_code: "de-AT" },
  { name: "AZERBAIJAN", currency_name: "AZN", currency_code: "az-Latn-AZ" },
  { name: "BAHAMAS (THE)", currency_name: "BSD", currency_code: "en-BS" },
  { name: "BAHRAIN", currency_name: "BHD", currency_code: "ar-BH" },
  { name: "BANGLADESH", currency_name: "BDT", currency_code: "bn-BD" },
  { name: "BARBADOS", currency_name: "BBD", currency_code: "en-BB" },
  { name: "BELARUS", currency_name: "BYN", currency_code: "be-BY" },
  { name: "BELGIUM", currency_name: "EUR", currency_code: "nl-BE" },
  { name: "BELIZE", currency_name: "BZD", currency_code: "en-BZ" },
  { name: "BENIN", currency_name: "XOF", currency_code: "fr-BJ" },
  { name: "BERMUDA", currency_name: "BMD", currency_code: "en-BM" },
  { name: "BHUTAN", currency_name: "INR", currency_code: "dz-BT" },
  { name: "BOLIVIA", currency_name: "BOB", currency_code: "es-BO" },
  {
    name: "BONAIRE, SINT EUSTATIUS AND SABA",
    currency_name: "USD",
    currency_code: "nl-BQ",
  },
  {
    name: "BOSNIA AND HERZEGOVINA",
    currency_name: "BAM",
    currency_code: "bs-Latn-BA",
  },
  { name: "BOTSWANA", currency_name: "BWP", currency_code: "en-BW" },
  { name: "BOUVET ISLAND", currency_name: "NOK", currency_code: "no-BV" },
  { name: "BRAZIL", currency_name: "BRL", currency_code: "pt-BR" },
  {
    name: "BRITISH INDIAN OCEAN TERRITORY (THE)",
    currency_name: "USD",
    currency_code: "en-IO",
  },
  { name: "BRUNEI DARUSSALAM", currency_name: "BND", currency_code: "ms-BN" },
  { name: "BULGARIA", currency_name: "BGN", currency_code: "bg-BG" },
  { name: "BURKINA FASO", currency_name: "XOF", currency_code: "fr-BF" },
  { name: "BURUNDI", currency_name: "BIF", currency_code: "fr-BI" },
  { name: "CABO VERDE", currency_name: "CVE", currency_code: "pt-CV" },
  { name: "CAMBODIA", currency_name: "KHR", currency_code: "km-KH" },
  { name: "CAMEROON", currency_name: "XAF", currency_code: "fr-CM" },
  { name: "CANADA", currency_name: "CAD", currency_code: "en-CA" },
  { name: "CAYMAN ISLANDS", currency_name: "KYD", currency_code: "en-KY" },
  {
    name: "CENTRAL AFRICAN REPUBLIC",
    currency_name: "XAF",
    currency_code: "fr-CF",
  },
  { name: "CHAD", currency_name: "XAF", currency_code: "fr-TD" },
  { name: "CHILE", currency_name: "CLP", currency_code: "es-CL" },
  { name: "CHINA", currency_name: "CNY", currency_code: "zh-CN" },
  { name: "CHRISTMAS ISLAND", currency_name: "AUD", currency_code: "en-CX" },
  {
    name: "COCOS (KEELING) ISLANDS (THE)",
    currency_name: "AUD",
    currency_code: "en-CK",
  },
  { name: "COLOMBIA", currency_name: "COP", currency_code: "es-CO" },
  { name: "COMOROS (THE)", currency_name: "KMF", currency_code: "ar-KM" },
  { name: "CONGO, DEMO. REP.", currency_name: "CDF", currency_code: "fr-CD" },
  { name: "CONGO (THE)", currency_name: "XAF", currency_code: "fr-CG" },
  { name: "COOK ISLANDS (THE)", currency_name: "NZD", currency_code: "en-CK" },
  { name: "COSTA RICA", currency_name: "CRC", currency_code: "es-CR" },
  { name: "CROATIA", currency_name: "EUR", currency_code: "hr-HR" },
  { name: "CUBA", currency_name: "CUP", currency_code: "es-CU" },
  { name: "CURAÇAO", currency_name: "ANG", currency_code: "nl-BQ" },
  { name: "CYPRUS", currency_name: "EUR", currency_code: "el-CY" },
  {
    name: "CZECH REPUBLIC (THE)",
    currency_name: "CZK",
    currency_code: "cs-CZ",
  },
  { name: "CÔTE D'IVOIRE", currency_name: "XOF", currency_code: "fr-CI" },
  { name: "DENMARK", currency_name: "DKK", currency_code: "da-DK" },
  { name: "DJIBOUTI", currency_name: "DJF", currency_code: "fr-DJ" },
  { name: "DOMINICA", currency_name: "XCD", currency_code: "en-DM" },
  {
    name: "DOMINICAN REPUBLIC (THE)",
    currency_name: "DOP",
    currency_code: "es-DO",
  },
  { name: "ECUADOR", currency_name: "USD", currency_code: "es-EC" },
  { name: "EGYPT", currency_name: "EGP", currency_code: "ar-EG" },
  { name: "EL SALVADOR", currency_name: "USD", currency_code: "es-SV" },
  { name: "EQUATORIAL GUINEA", currency_name: "XAF", currency_code: "fr-GQ" },
  { name: "ERITREA", currency_name: "ERN", currency_code: "ti-ER" },
  { name: "ESTONIA", currency_name: "EUR", currency_code: "et-EE" },
  { name: "ETHIOPIA", currency_name: "ETB", currency_code: "am-ET" },
  { name: "EUROPEAN UNION", currency_name: "EUR", currency_code: "en-EU" },
  {
    name: "FALKLAND ISLANDS (THE) [MALVINAS]",
    currency_name: "FKP",
    currency_code: "en-FK",
  },
  { name: "FAROE ISLANDS (THE)", currency_name: "DKK", currency_code: "fo-FO" },
  { name: "FIJI", currency_name: "FJD", currency_code: "en-FJ" },
  { name: "FINLAND", currency_name: "EUR", currency_code: "fi-FI" },
  { name: "FRANCE", currency_name: "EUR", currency_code: "fr-FR" },
  { name: "FRENCH GUIANA", currency_name: "EUR", currency_code: "fr-GF" },
  { name: "FRENCH POLYNESIA", currency_name: "XPF", currency_code: "fr-PF" },
  {
    name: "FRENCH SOUTHERN TERRITORIES (THE)",
    currency_name: "EUR",
    currency_code: "fr-TF",
  },
  { name: "GABON", currency_name: "XAF", currency_code: "fr-GA" },
  { name: "GAMBIA (THE)", currency_name: "GMD", currency_code: "en-GM" },
  { name: "GEORGIA", currency_name: "GEL", currency_code: "ka-GE" },
  { name: "GERMANY", currency_name: "EUR", currency_code: "de-DE" },
  { name: "GHANA", currency_name: "GHS", currency_code: "en-GH" },
  { name: "GIBRALTAR", currency_name: "GIP", currency_code: "en-GI" },
  { name: "GREECE", currency_name: "EUR", currency_code: "el-GR" },
  { name: "GREENLAND", currency_name: "DKK", currency_code: "kl-GL" },
  { name: "GRENADA", currency_name: "XCD", currency_code: "en-GD" },
  { name: "GUADELOUPE", currency_name: "EUR", currency_code: "fr-GP" },
  { name: "GUAM", currency_name: "USD", currency_code: "en-GU" },
  { name: "GUATEMALA", currency_name: "GTQ", currency_code: "es-GT" },
  { name: "GUERNSEY", currency_name: "GBP", currency_code: "en-GG" },
  { name: "GUINEA", currency_name: "GNF", currency_code: "fr-GN" },
  { name: "GUINEA-BISSAU", currency_name: "XOF", currency_code: "pt-GW" },
  { name: "GUYANA", currency_name: "GYD", currency_code: "en-GY" },
  { name: "HAITI", currency_name: "HTG", currency_code: "ht-HT" },
  {
    name: "HEARD ISLAND AND McDONALD ISLANDS",
    currency_name: "AUD",
    currency_code: "en-HM",
  },
  { name: "HOLY SEE (THE)", currency_name: "EUR", currency_code: "it-VA" },
  { name: "HONDURAS", currency_name: "HNL", currency_code: "es-HN" },
  { name: "HONG KONG", currency_name: "HKD", currency_code: "zh-HK" },
  { name: "HUNGARY", currency_name: "HUF", currency_code: "hu-HU" },
  { name: "ICELAND", currency_name: "ISK", currency_code: "is-IS" },
  { name: "INDIA", currency_name: "INR", currency_code: "hi-IN" },
  { name: "INDONESIA", currency_name: "IDR", currency_code: "id-ID" },
  {
    name: "INTERNATIONAL MONETARY FUND (IMF) ",
    currency_name: "XDR",
    currency_code: "en-US",
  },
  {
    name: "IRAN (ISLAMIC REPUBLIC OF)",
    currency_name: "IRR",
    currency_code: "fa-IR",
  },
  { name: "IRAQ", currency_name: "IQD", currency_code: "ar-IQ" },
  { name: "IRELAND", currency_name: "EUR", currency_code: "ga-IE" },
  { name: "ISLE OF MAN", currency_name: "GBP", currency_code: "en-IM" },
  { name: "ISRAEL", currency_name: "ILS", currency_code: "he-IL" },
  { name: "ITALY", currency_name: "EUR", currency_code: "it-IT" },
  { name: "JAMAICA", currency_name: "JMD", currency_code: "en-JM" },
  { name: "JAPAN", currency_name: "JPY", currency_code: "ja-JP" },
  { name: "JERSEY", currency_name: "GBP", currency_code: "en-JE" },
  { name: "JORDAN", currency_name: "JOD", currency_code: "ar-JO" },
  { name: "KAZAKHSTAN", currency_name: "KZT", currency_code: "kk-KZ" },
  { name: "KENYA", currency_name: "KES", currency_code: "en-KE" },
  { name: "KIRIBATI", currency_name: "AUD", currency_code: "en-KI" },
  {
    name: "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)",
    currency_name: "KPW",
    currency_code: "ko-KP",
  },
  {
    name: "KOREA (THE REPUBLIC OF)",
    currency_name: "KRW",
    currency_code: "ko-KR",
  },
  { name: "KUWAIT", currency_name: "KWD", currency_code: "ar-KW" },
  { name: "KYRGYZSTAN", currency_name: "KGS", currency_code: "ky-KG" },
  {
    name: "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)",
    currency_name: "LAK",
    currency_code: "lo-LA",
  },
  { name: "LATVIA", currency_name: "EUR", currency_code: "lv-LV" },
  { name: "LEBANON", currency_name: "LBP", currency_code: "ar-LB" },
  { name: "LESOTHO", currency_name: "LSL", currency_code: "en-LS" },
  { name: "LIBERIA", currency_name: "LRD", currency_code: "en-LR" },
  { name: "LIBYA", currency_name: "LYD", currency_code: "ar-LY" },
  { name: "LIECHTENSTEIN", currency_name: "CHF", currency_code: "de-LI" },
  { name: "LITHUANIA", currency_name: "EUR", currency_code: "lt-LT" },
  { name: "LUXEMBOURG", currency_name: "EUR", currency_code: "lb-LU" },
  { name: "MACAO", currency_name: "MOP", currency_code: "zh-MO" },
  { name: "MADAGASCAR", currency_name: "MGA", currency_code: "mg-MG" },
  { name: "MALAWI", currency_name: "MWK", currency_code: "ny-MW" },
  { name: "MALAYSIA", currency_name: "MYR", currency_code: "ms-MY" },
  { name: "MALDIVES", currency_name: "MVR", currency_code: "dv-MV" },
  { name: "MALI", currency_name: "XOF", currency_code: "fr-ML" },
  { name: "MALTA", currency_name: "EUR", currency_code: "mt-MT" },
  {
    name: "MARSHALL ISLANDS (THE)",
    currency_name: "USD",
    currency_code: "en-MH",
  },
  { name: "MARTINIQUE", currency_name: "EUR", currency_code: "fr-MQ" },
  { name: "MAURITANIA", currency_name: "MRU", currency_code: "ar-MR" },
  { name: "MAURITIUS", currency_name: "MUR", currency_code: "en-MU" },
  { name: "MAYOTTE", currency_name: "EUR", currency_code: "fr-YT" },
  {
    name: "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP",
    currency_name: "XUA",
    currency_code: "en-US",
  },
  { name: "MEXICO", currency_name: "MXN", currency_code: "es-MX" },
  {
    name: "MICRONESIA (FEDERATED STATES OF)",
    currency_name: "USD",
    currency_code: "en-FM",
  },
  {
    name: "MOLDOVA (THE REPUBLIC OF)",
    currency_name: "MDL",
    currency_code: "ro-MD",
  },
  { name: "MONACO", currency_name: "EUR", currency_code: "fr-MC" },
  { name: "MONGOLIA", currency_name: "MNT", currency_code: "mn-mn" },
  { name: "MONTENEGRO", currency_name: "EUR", currency_code: "sr-Latn-ME" },
  { name: "MONTSERRAT", currency_name: "XCD", currency_code: "en-MS" },
  { name: "MOROCCO", currency_name: "MAD", currency_code: "ar-MA" },
  { name: "MOZAMBIQUE", currency_name: "MZN", currency_code: "pt-MZ" },
  { name: "MYANMAR", currency_name: "MMK", currency_code: "my-MM" },
  { name: "NAMIBIA", currency_name: "NAD", currency_code: "af-NA" },
  { name: "NAURU", currency_name: "AUD", currency_code: "en-NR" },
  { name: "NEPAL", currency_name: "NPR", currency_code: "ne-NP" },
  { name: "NETHERLANDS (THE)", currency_name: "EUR", currency_code: "nl-NL" },
  { name: "NEW CALEDONIA", currency_name: "XPF", currency_code: "fr-NC" },
  { name: "NEW ZEALAND", currency_name: "NZD", currency_code: "en-NZ" },
  { name: "NICARAGUA", currency_name: "NIO", currency_code: "es-NI" },
  { name: "NIGER (THE)", currency_name: "XOF", currency_code: "fr-NE" },
  { name: "NIGERIA", currency_name: "NGN", currency_code: "en-NG" },
  { name: "NIUE", currency_name: "NZD", currency_code: "en-NU" },
  { name: "NORFOLK ISLAND", currency_name: "AUD", currency_code: "en-NF" },
  {
    name: "NORTHERN MARIANA ISLANDS (THE)",
    currency_name: "USD",
    currency_code: "en-MP",
  },
  { name: "NORWAY", currency_name: "NOK", currency_code: "nb-NO" },
  { name: "OMAN", currency_name: "OMR", currency_code: "ar-OM" },
  { name: "PAKISTAN", currency_name: "PKR", currency_code: "ur-PK" },
  { name: "PALAU", currency_name: "USD", currency_code: "en-PW" },
  { name: "PALESTINE, STATE OF", currency_name: "", currency_code: "ar-PS" },
  { name: "PANAMA", currency_name: "PAB", currency_code: "es-PA" },
  { name: "PAPUA NEW GUINEA", currency_name: "PGK", currency_code: "en-PG" },
  { name: "PARAGUAY", currency_name: "PYG", currency_code: "es-PY" },
  { name: "PERU", currency_name: "PEN", currency_code: "es-PE" },
  { name: "PHILIPPINES (THE)", currency_name: "PHP", currency_code: "fil-PH" },
  { name: "PITCAIRN", currency_name: "NZD", currency_code: "en-PN" },
  { name: "POLAND", currency_name: "PLN", currency_code: "pl-PL" },
  { name: "PORTUGAL", currency_name: "EUR", currency_code: "pt-PT" },
  { name: "PUERTO RICO", currency_name: "USD", currency_code: "en-PR" },
  { name: "QATAR", currency_name: "QAR", currency_code: "ar-QA" },
  {
    name: "REPUBLIC OF NORTH MACEDONIA",
    currency_name: "MKD",
    currency_code: "mk-MK",
  },
  { name: "ROMANIA", currency_name: "RON", currency_code: "ro-RO" },
  { name: "RUSSIAN FEDERATION", currency_name: "RUB", currency_code: "ru-RU" },
  { name: "RWANDA", currency_name: "RWF", currency_code: "rw-RW" },
  { name: "RÉUNION", currency_name: "EUR", currency_code: "fr-RE" },
  { name: "SAINT BARTHÉLEMY", currency_name: "EUR", currency_code: "fr-BL" },
  {
    name: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
    currency_name: "SHP",
    currency_code: "en-SH",
  },
  {
    name: "SAINT KITTS AND NEVIS",
    currency_name: "XCD",
    currency_code: "en-KN",
  },
  { name: "SAINT LUCIA", currency_name: "XCD", currency_code: "en-LC" },
  {
    name: "SAINT MARTIN (FRENCH PART)",
    currency_name: "EUR",
    currency_code: "fr-MF",
  },
  {
    name: "SAINT PIERRE AND MIQUELON",
    currency_name: "EUR",
    currency_code: "fr-PM",
  },
  {
    name: "SAINT VINCENT AND THE GRENADINES",
    currency_name: "XCD",
    currency_code: "en-VC",
  },
  { name: "SAMOA", currency_name: "WST", currency_code: "sm-WS" },
  { name: "SAN MARINO", currency_name: "EUR", currency_code: "it-SM" },
  {
    name: "SAO TOME AND PRINCIPE",
    currency_name: "STN",
    currency_code: "pt-ST",
  },
  { name: "SAUDI ARABIA", currency_name: "SAR", currency_code: "ar-SA" },
  { name: "SENEGAL", currency_name: "XOF", currency_code: "fr-SN" },
  { name: "SERBIA", currency_name: "RSD", currency_code: "sr-Cyrl-RS" },
  { name: "SEYCHELLES", currency_name: "SCR", currency_code: "en-SC" },
  { name: "SIERRA LEONE", currency_name: "SLE", currency_code: "en-SL" },
  { name: "SINGAPORE", currency_name: "SGD", currency_code: "en-SG" },
  {
    name: "SINT MAARTEN (DUTCH PART)",
    currency_name: "ANG",
    currency_code: "nl-SX",
  },
  {
    name: "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOs",
    currency_name: "XSU",
    currency_code: "es-EC",
  },
  { name: "SLOVAKIA", currency_name: "EUR", currency_code: "sk-SK" },
  { name: "SLOVENIA", currency_name: "EUR", currency_code: "sl-SI" },
  { name: "SOLOMON ISLANDS", currency_name: "SBD", currency_code: "en-SB" },
  { name: "SOMALIA", currency_name: "SOS", currency_code: "so-SO" },
  { name: "SOUTH AFRICA", currency_name: "ZAR", currency_code: "af-ZA" },
  {
    name: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    currency_name: "",
    currency_code: "en-GS",
  },
  { name: "SOUTH SUDAN", currency_name: "SSP", currency_code: "en-SS" },
  { name: "SPAIN", currency_name: "EUR", currency_code: "es-ES" },
  { name: "SRI LANKA", currency_name: "LKR", currency_code: "si-LK" },
  { name: "SUDAN (THE)", currency_name: "SDG", currency_code: "ar-SD" },
  { name: "SURINAME", currency_name: "SRD", currency_code: "nl-SR" },
  {
    name: "SVALBARD AND JAN MAYEN",
    currency_name: "NOK",
    currency_code: "no-SJ",
  },
  { name: "SWAZILAND", currency_name: "SZL", currency_code: "en-SZ" },
  { name: "SWEDEN", currency_name: "SEK", currency_code: "sv-SE" },
  { name: "SWITZERLAND", currency_name: "CHF", currency_code: "de-CH" },
  {
    name: "SYRIAN ARAB REPUBLIC",
    currency_name: "SYP",
    currency_code: "ar-SY",
  },
  {
    name: "TAIWAN (PROVINCE OF CHINA)",
    currency_name: "TWD",
    currency_code: "zh-TW",
  },
  { name: "TAJIKISTAN", currency_name: "TJS", currency_code: "tg-TJ" },
  {
    name: "TANZANIA, UNITED REPUBLIC OF",
    currency_name: "TZS",
    currency_code: "sw-TZ",
  },
  { name: "THAILAND", currency_name: "THB", currency_code: "th-TH" },
  { name: "TIMOR-LESTE", currency_name: "USD", currency_code: "tet-TL" },
  { name: "TOGO", currency_name: "XOF", currency_code: "fr-TG" },
  { name: "TOKELAU", currency_name: "NZD", currency_code: "en-TK" },
  { name: "TONGA", currency_name: "TOP", currency_code: "to-TO" },
  { name: "TRINIDAD AND TOBAGO", currency_name: "TTD", currency_code: "en-TT" },
  { name: "TUNISIA", currency_name: "TND", currency_code: "ar-TN" },
  { name: "TURKEY", currency_name: "TRY", currency_code: "tr-TR" },
  { name: "TURKMENISTAN", currency_name: "TMT", currency_code: "tk-TM" },
  {
    name: "TURKS AND CAICOS ISLANDS",
    currency_name: "USD",
    currency_code: "en-TC",
  },
  { name: "TUVALU", currency_name: "AUD", currency_code: "en-TV" },
  { name: "UGANDA", currency_name: "UGX", currency_code: "en-UG" },
  { name: "UKRAINE", currency_name: "UAH", currency_code: "uk-UA" },
  {
    name: "UNITED ARAB EMIRATES",
    currency_name: "AED",
    currency_code: "ar-AE",
  },
  { name: "UNITED KINGDOM", currency_name: "GBP", currency_code: "en-GB" },
  {
    name: "UNITED STATES MINOR OUTLYING ISLANDS (THE)",
    currency_name: "USD",
    currency_code: "en-UM",
  },
  { name: "UNITED STATES", currency_name: "USD", currency_code: "en-US" },
  { name: "URUGUAY", currency_name: "UYU", currency_code: "es-UY" },
  { name: "UZBEKISTAN", currency_name: "UZS", currency_code: "uz-Latn-UZ" },
  { name: "VANUATU", currency_name: "VUV", currency_code: "bi-VU" },
  {
    name: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    currency_name: "VES",
    currency_code: "es-VE",
  },
  { name: "VIET NAM", currency_name: "VND", currency_code: "vi-VN" },
  {
    name: "VIRGIN ISLANDS (BRITISH)",
    currency_name: "USD",
    currency_code: "en-VG",
  },
  {
    name: "VIRGIN ISLANDS (U.S.)",
    currency_name: "USD",
    currency_code: "en-VI",
  },
  { name: "WALLIS AND FUTUNA", currency_name: "XPF", currency_code: "fr-WF" },
  { name: "WESTERN SAHARA", currency_name: "MAD", currency_code: "ar-DZ" },
  { name: "YEMEN", currency_name: "YER", currency_code: "ar-YE" },
  { name: "ZAMBIA", currency_name: "ZMW", currency_code: "en-ZM" },
  { name: "ZIMBABWE", currency_name: "ZWL", currency_code: "en-ZW" },
  { name: "ÅLAND ISLANDS", currency_name: "EUR", currency_code: "sv-FI" },
];

export default CURRENCY_CODES;
