const CURRENCY_CODES = [
  { name: "AFGHANISTAN", currency_name: "AFN", currency_code: "tk-AF" },
  { name: "ALBANIA", currency_name: "ALL", currency_code: "en-US" },
  { name: "ALGERIA", currency_name: "DZD", currency_code: "en-US" },
  { name: "AMERICAN SAMOA", currency_name: "USD", currency_code: "en-US" },
  { name: "ANDORRA", currency_name: "EUR", currency_code: "en-US" },
  { name: "ANGOLA", currency_name: "AOA", currency_code: "fr-XC" },
  { name: "ANGUILLA", currency_name: "XCD", currency_code: "es-XC" },
  { name: "ANTARCTICA", currency_name: "", currency_code: "zh-XC" },
  { name: "ANTIGUA AND BARBUDA", currency_name: "XCD", currency_code: "es-XC" },
  { name: "ARGENTINA", currency_name: "ARS", currency_code: "en-US" },
  { name: "ARMENIA", currency_name: "AMD", currency_code: "en-US" },
  { name: "ARUBA", currency_name: "AWG", currency_code: "fr-XC" },
  { name: "AUSTRALIA", currency_name: "AUD", currency_code: "es-XC" },
  { name: "AUSTRIA", currency_name: "EUR", currency_code: "zh-XC" },
  { name: "AZERBAIJAN", currency_name: "AZN", currency_code: "en-US" },
  { name: "BAHAMAS (THE)", currency_name: "BSD", currency_code: "fr-XC" },
  { name: "BAHRAIN", currency_name: "BHD", currency_code: "es-XC" },
  { name: "BANGLADESH", currency_name: "BDT", currency_code: "en-IN" },
  { name: "BARBADOS", currency_name: "BBD", currency_code: "en-AU" },
  { name: "BELARUS", currency_name: "BYN", currency_code: "de-DE" },
  { name: "BELGIUM", currency_name: "EUR", currency_code: "en-US" },
  { name: "BELIZE", currency_name: "BZD", currency_code: "en-US" },
  { name: "BENIN", currency_name: "XOF", currency_code: "fr-XC" },
  { name: "BERMUDA", currency_name: "BMD", currency_code: "es-XC" },
  { name: "BHUTAN", currency_name: "INR", currency_code: "en-IN" },
  { name: "BOLIVIA", currency_name: "BOB", currency_code: "fr-XC" },
  {
    name: "BONAIRE, SINT EUSTATIUS AND SABA",
    currency_name: "USD",
    currency_code: "zh-XC",
  },
  {
    name: "BOSNIA AND HERZEGOVINA",
    currency_name: "BAM",
    currency_code: "ar-EG",
  },
  { name: "BOTSWANA", currency_name: "BWP", currency_code: "en-US" },
  { name: "BOUVET ISLAND", currency_name: "NOK", currency_code: "fr-XC" },
  { name: "BRAZIL", currency_name: "BRL", currency_code: "es-XC" },
  {
    name: "BRITISH INDIAN OCEAN TERRITORY (THE)",
    currency_name: "USD",
    currency_code: "zh-XC",
  },
  { name: "BRUNEI DARUSSALAM", currency_name: "BND", currency_code: "en-US" },
  { name: "BULGARIA", currency_name: "BGN", currency_code: "fr-XC" },
  { name: "BURKINA FASO", currency_name: "XOF", currency_code: "es-XC" },
  { name: "BURUNDI", currency_name: "BIF", currency_code: "zh-XC" },
  { name: "CABO VERDE", currency_name: "CVE", currency_code: "en-US" },
  { name: "CAMBODIA", currency_name: "KHR", currency_code: "en-US" },
  { name: "CAMEROON", currency_name: "XAF", currency_code: "nl-NL" },
  { name: "CANADA", currency_name: "CAD", currency_code: "en-CD" },
  {
    name: "CAYMAN ISLANDS",
    currency_name: "KYD",
    currency_code: "es-XC",
  },
  {
    name: "CENTRAL AFRICAN REPUBLIC",
    currency_name: "XAF",
    currency_code: "en-US",
  },
  { name: "CHAD", currency_name: "XAF", currency_code: "fr-XC" },
  { name: "CHILE", currency_name: "CLF", currency_code: "zh-XC" },
  { name: "CHILE", currency_name: "CLP", currency_code: "fr-XC" },
  { name: "CHINA", currency_name: "CNY", currency_code: "en-US" },
  { name: "CHRISTMAS ISLAND", currency_name: "AUD", currency_code: "es-XC" },
  {
    name: "COCOS (KEELING) ISLANDS (THE)",
    currency_name: "AUD",
    currency_code: "zh-XC",
  },
  { name: "COLOMBIA", currency_name: "COP", currency_code: "en-US" },
  { name: "COLOMBIA", currency_name: "COU", currency_code: "fr-XC" },
  { name: "COMOROS (THE)", currency_name: "KMF", currency_code: "es-XC" },
  {
    name: "CONGO, DEMO. REP.",
    currency_name: "CDF",
    currency_code: "zh-XC",
  },
  { name: "CONGO (THE)", currency_name: "XAF", currency_code: "en-US" },
  { name: "COOK ISLANDS (THE)", currency_name: "NZD", currency_code: "es-XC" },
  { name: "COSTA RICA", currency_name: "CRC", currency_code: "en-US" },
  { name: "CROATIA", currency_name: "EUR", currency_code: "fr-XC" },
  { name: "CUBA", currency_name: "CUC", currency_code: "zh-XC" },
  { name: "CUBA", currency_name: "CUP", currency_code: "en-US" },
  { name: "CURAÇAO", currency_name: "ANG", currency_code: "en-US" },
  { name: "CYPRUS", currency_name: "EUR", currency_code: "fr-XC" },
  {
    name: "CZECH REPUBLIC (THE)",
    currency_name: "CZK",
    currency_code: "es-XC",
  },
  { name: "CÔTE D'IVOIRE", currency_name: "XOF", currency_code: "zh-XC" },
  { name: "DENMARK", currency_name: "DKK", currency_code: "pt-BR" },
  { name: "DJIBOUTI", currency_name: "DJF", currency_code: "en-US" },
  { name: "DOMINICA", currency_name: "XCD", currency_code: "en-US" },
  {
    name: "DOMINICAN REPUBLIC (THE)",
    currency_name: "DOP",
    currency_code: "fr-XC",
  },
  { name: "ECUADOR", currency_name: "USD", currency_code: "es-XC" },
  { name: "EGYPT", currency_name: "EGP", currency_code: "zh-XC" },
  { name: "EL SALVADOR", currency_name: "SVC", currency_code: "en-US" },
  { name: "EL SALVADOR", currency_name: "USD", currency_code: "en-US" },
  { name: "EQUATORIAL GUINEA", currency_name: "XAF", currency_code: "fr-XC" },
  { name: "ERITREA", currency_name: "ERN", currency_code: "en-US" },
  { name: "ESTONIA", currency_name: "EUR", currency_code: "es-XC" },
  { name: "ETHIOPIA", currency_name: "ETB", currency_code: "zh-XC" },
  { name: "EUROPEAN UNION", currency_name: "EUR", currency_code: "fr-XC" },
  {
    name: "FALKLAND ISLANDS (THE) [MALVINAS]",
    currency_name: "FKP",
    currency_code: "en-US",
  },
  { name: "FAROE ISLANDS (THE)", currency_name: "DKK", currency_code: "es-XC" },
  { name: "FIJI", currency_name: "FJD", currency_code: "en-FJ" },
  { name: "FINLAND", currency_name: "EUR", currency_code: "en-US" },
  { name: "FRANCE", currency_name: "EUR", currency_code: "fr-XC" },
  { name: "FRENCH GUIANA", currency_name: "EUR", currency_code: "en-US" },
  { name: "FRENCH POLYNESIA", currency_name: "XPF", currency_code: "en-US" },
  {
    name: "FRENCH SOUTHERN TERRITORIES (THE)",
    currency_name: "EUR",
    currency_code: "fr-CA",
  },
  { name: "GABON", currency_name: "XAF", currency_code: "en-US" },
  { name: "GAMBIA (THE)", currency_name: "GMD", currency_code: "fr-XC" },
  { name: "GEORGIA", currency_name: "GEL", currency_code: "es-XC" },
  { name: "GERMANY", currency_name: "EUR", currency_code: "zh-XC" },
  { name: "GHANA", currency_name: "GHS", currency_code: "en-US" },
  { name: "GIBRALTAR", currency_name: "GIP", currency_code: "fr-XC" },
  { name: "GREECE", currency_name: "EUR", currency_code: "es-XC" },
  { name: "GREENLAND", currency_name: "DKK", currency_code: "zh-XC" },
  { name: "GRENADA", currency_name: "XCD", currency_code: "fr-XC" },
  { name: "GUADELOUPE", currency_name: "EUR", currency_code: "en-US" },
  { name: "GUAM", currency_name: "USD", currency_code: "es-XC" },
  { name: "GUATEMALA", currency_name: "GTQ", currency_code: "zh-XC" },
  { name: "GUERNSEY", currency_name: "GBP", currency_code: "es-XC" },
  { name: "GUINEA", currency_name: "GNF", currency_code: "en-US" },
  { name: "GUINEA-BISSAU", currency_name: "XOF", currency_code: "fr-XC" },
  { name: "GUYANA", currency_name: "GYD", currency_code: "zh-XC" },
  { name: "HAITI", currency_name: "HTG", currency_code: "zh-CN" },
  { name: "HAITI", currency_name: "USD", currency_code: "zh-XC" },
  {
    name: "HEARD ISLAND AND McDONALD ISLANDS",
    currency_name: "AUD",
    currency_code: "en-US",
  },
  { name: "HOLY SEE (THE)", currency_name: "EUR", currency_code: "es-XC" },
  { name: "HONDURAS", currency_name: "HNL", currency_code: "en-US" },
  { name: "HONG KONG", currency_name: "HKD", currency_code: "fr-XC" },
  { name: "HUNGARY", currency_name: "HUF", currency_code: "zh-XC" },
  { name: "ICELAND", currency_name: "ISK", currency_code: "fr-XC" },
  { name: "INDIA", currency_name: "INR", currency_code: "en-IN" },
  { name: "INDONESIA", currency_name: "IDR", currency_code: "es-XC" },
  {
    name: "INTERNATIONAL MONETARY FUND (IMF) ",
    currency_name: "XDR",
    currency_code: "zh-XC",
  },
  {
    name: "IRAN (ISLAMIC REPUBLIC OF)",
    currency_name: "IRR",
    currency_code: "en-US",
  },
  { name: "IRAQ", currency_name: "IQD", currency_code: "fr-XC" },
  { name: "IRELAND", currency_name: "EUR", currency_code: "es-XC" },
  { name: "ISLE OF MAN", currency_name: "GBP", currency_code: "zh-XC" },
  { name: "ISRAEL", currency_name: "ILS", currency_code: "fr-XC" },
  { name: "ITALY", currency_name: "EUR", currency_code: "en-US" },
  { name: "JAMAICA", currency_name: "JMD", currency_code: "es-XC" },
  { name: "JAPAN", currency_name: "JPY", currency_code: "zh-XC" },
  { name: "JERSEY", currency_name: "GBP", currency_code: "en-US" },
  { name: "JORDAN", currency_name: "JOD", currency_code: "fr-XC" },
  { name: "KAZAKHSTAN", currency_name: "KZT", currency_code: "es-XC" },
  { name: "KENYA", currency_name: "KES", currency_code: "zh-XC" },
  { name: "KIRIBATI", currency_name: "AUD", currency_code: "es-XC" },
  {
    name: "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)",
    currency_name: "KPW",
    currency_code: "en-US",
  },
  {
    name: "KOREA (THE REPUBLIC OF)",
    currency_name: "KRW",
    currency_code: "fr-XC",
  },
  { name: "KUWAIT", currency_name: "KWD", currency_code: "zh-XC" },
  { name: "KYRGYZSTAN", currency_name: "KGS", currency_code: "fr-XC" },
  {
    name: "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)",
    currency_name: "LAK",
    currency_code: "en-US",
  },
  { name: "LATVIA", currency_name: "EUR", currency_code: "en-US" },
  { name: "LEBANON", currency_name: "LBP", currency_code: "en-US" },
  { name: "LESOTHO", currency_name: "LSL", currency_code: "cs-CZ" },
  { name: "LESOTHO", currency_name: "ZAR", currency_code: "en-US" },
  { name: "LIBERIA", currency_name: "LRD", currency_code: "fr-XC" },
  { name: "LIBYA", currency_name: "LYD", currency_code: "es-XC" },
  { name: "LIECHTENSTEIN", currency_name: "CHF", currency_code: "zh-XC" },
  { name: "LITHUANIA", currency_name: "EUR", currency_code: "da-DK" },
  { name: "LUXEMBOURG", currency_name: "EUR", currency_code: "en-US" },
  { name: "MACAO", currency_name: "MOP", currency_code: "fr-XC" },
  { name: "MADAGASCAR", currency_name: "MGA", currency_code: "en-US" },
  { name: "MALAWI", currency_name: "MWK", currency_code: "es-XC" },
  { name: "MALAYSIA", currency_name: "MYR", currency_code: "zh-XC" },
  { name: "MALDIVES", currency_name: "MVR", currency_code: "en-US" },
  { name: "MALI", currency_name: "XOF", currency_code: "fr-XC" },
  { name: "MALTA", currency_name: "EUR", currency_code: "es-XC" },
  {
    name: "MARSHALL ISLANDS (THE)",
    currency_name: "USD",
    currency_code: "zh-XC",
  },
  { name: "MARTINIQUE", currency_name: "EUR", currency_code: "es-XC" },
  { name: "MAURITANIA", currency_name: "MRU", currency_code: "en-US" },
  { name: "MAURITIUS", currency_name: "MUR", currency_code: "fr-XC" },
  { name: "MAYOTTE", currency_name: "EUR", currency_code: "zh-XC" },
  {
    name: "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP",
    currency_name: "XUA",
    currency_code: "es-XC",
  },
  { name: "MEXICO", currency_name: "MXN", currency_code: "en-US" },
  { name: "MEXICO", currency_name: "MXV", currency_code: "fr-XC" },
  {
    name: "MICRONESIA (FEDERATED STATES OF)",
    currency_name: "USD",
    currency_code: "zh-XC",
  },
  {
    name: "MOLDOVA (THE REPUBLIC OF)",
    currency_name: "MDL",
    currency_code: "ar-EG",
  },
  { name: "MONACO", currency_name: "EUR", currency_code: "en-US" },
  { name: "MONGOLIA", currency_name: "MNT", currency_code: "fr-XC" },
  { name: "MONTENEGRO", currency_name: "EUR", currency_code: "es-XC" },
  { name: "MONTSERRAT", currency_name: "XCD", currency_code: "zh-XC" },
  { name: "MOROCCO", currency_name: "MAD", currency_code: "es-XC" },
  { name: "MOZAMBIQUE", currency_name: "MZN", currency_code: "en-US" },
  { name: "MYANMAR", currency_name: "MMK", currency_code: "fr-XC" },
  { name: "NAMIBIA", currency_name: "NAD", currency_code: "zh-XC" },
  { name: "NAMIBIA", currency_name: "ZAR", currency_code: "en-US" },
  { name: "NAURU", currency_name: "AUD", currency_code: "fr-XC" },
  { name: "NEPAL", currency_name: "NPR", currency_code: "en-IN" },
  { name: "NETHERLANDS (THE)", currency_name: "EUR", currency_code: "zh-XC" },
  { name: "NEW CALEDONIA", currency_name: "XPF", currency_code: "en-US" },
  { name: "NEW ZEALAND", currency_name: "NZD", currency_code: "ru-RU" },
  { name: "NICARAGUA", currency_name: "NIO", currency_code: "fr-XC" },
  { name: "NIGER (THE)", currency_name: "XOF", currency_code: "es-XC" },
  { name: "NIGERIA", currency_name: "NGN", currency_code: "zh-XC" },
  { name: "NIUE", currency_name: "NZD", currency_code: "en-US" },
  { name: "NORFOLK ISLAND", currency_name: "AUD", currency_code: "fr-XC" },
  {
    name: "NORTHERN MARIANA ISLANDS (THE)",
    currency_name: "USD",
    currency_code: "es-XC",
  },
  { name: "NORWAY", currency_name: "NOK", currency_code: "zh-XC" },
  { name: "OMAN", currency_name: "OMR", currency_code: "en-US" },
  { name: "PAKISTAN", currency_name: "PKR", currency_code: "en-IN" },
  { name: "PALAU", currency_name: "USD", currency_code: "es-XC" },
  { name: "PALESTINE, STATE OF", currency_name: "", currency_code: "zh-XC" },
  { name: "PANAMA", currency_name: "PAB", currency_code: "da-DK" },
  { name: "PANAMA", currency_name: "USD", currency_code: "en-US" },
  { name: "PAPUA NEW GUINEA", currency_name: "PGK", currency_code: "fr-XC" },
  { name: "PARAGUAY", currency_name: "PYG", currency_code: "es-XC" },
  { name: "PERU", currency_name: "PEN", currency_code: "zh-XC" },
  { name: "PHILIPPINES (THE)", currency_name: "PHP", currency_code: "en-US" },
  { name: "PITCAIRN", currency_name: "NZD", currency_code: "fr-XC" },
  { name: "POLAND", currency_name: "PLN", currency_code: "es-XC" },
  { name: "PORTUGAL", currency_name: "EUR", currency_code: "zh-XC" },
  { name: "PUERTO RICO", currency_name: "USD", currency_code: "fi-FI" },
  { name: "QATAR", currency_name: "QAR", currency_code: "en-US" },
  {
    name: "REPUBLIC OF NORTH MACEDONIA",
    currency_name: "MKD",
    currency_code: "fr-XC",
  },
  { name: "ROMANIA", currency_name: "RON", currency_code: "es-XC" },
  {
    name: "RUSSIAN FEDERATION",
    currency_name: "RUB",
    currency_code: "ru-BY",
  },
  { name: "RWANDA", currency_name: "RWF", currency_code: "fr-FR" },
  { name: "RÉUNION", currency_name: "EUR", currency_code: "en-US" },
  { name: "SAINT BARTHÉLEMY", currency_name: "EUR", currency_code: "en-US" },
  {
    name: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
    currency_name: "SHP",
    currency_code: "fr-XC",
  },
  {
    name: "SAINT KITTS AND NEVIS",
    currency_name: "XCD",
    currency_code: "es-XC",
  },
  { name: "SAINT LUCIA", currency_name: "XCD", currency_code: "zh-XC" },
  {
    name: "SAINT MARTIN (FRENCH PART)",
    currency_name: "EUR",
    currency_code: "en-US",
  },
  {
    name: "SAINT PIERRE AND MIQUELON",
    currency_name: "EUR",
    currency_code: "fr-XC",
  },
  {
    name: "SAINT VINCENT AND THE GRENADINES",
    currency_name: "XCD",
    currency_code: "es-XC",
  },
  { name: "SAMOA", currency_name: "WST", currency_code: "zh-XC" },
  { name: "SAN MARINO", currency_name: "EUR", currency_code: "fr-XC" },
  {
    name: "SAO TOME AND PRINCIPE",
    currency_name: "STN",
    currency_code: "en-US",
  },
  { name: "SAUDI ARABIA", currency_name: "SAR", currency_code: "ar-SA" },
  { name: "SENEGAL", currency_name: "XOF", currency_code: "zh-XC" },
  { name: "SERBIA", currency_name: "RSD", currency_code: "sr-RS" },
  { name: "SEYCHELLES", currency_name: "SCR", currency_code: "en-SC" },
  { name: "SIERRA LEONE", currency_name: "SLE", currency_code: "es-XC" },
  { name: "SINGAPORE", currency_name: "SGD", currency_code: "en-SG" },
  {
    name: "SINT MAARTEN (DUTCH PART)",
    currency_name: "ANG",
    currency_code: "en-US",
  },
  {
    name: 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"',
    currency_name: "XSU",
    currency_code: "fr-XC",
  },
  { name: "SLOVAKIA", currency_name: "EUR", currency_code: "es-XC" },
  { name: "SLOVENIA", currency_name: "EUR", currency_code: "zh-XC" },
  { name: "SOLOMON ISLANDS", currency_name: "SBD", currency_code: "de-DE" },
  { name: "SOMALIA", currency_name: "SOS", currency_code: "en-US" },
  { name: "SOUTH AFRICA", currency_name: "ZAR", currency_code: "en-US" },
  {
    name: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    currency_name: "",
    currency_code: "fr-XC",
  },
  { name: "SOUTH SUDAN", currency_name: "SSP", currency_code: "es-XC" },
  { name: "SPAIN", currency_name: "EUR", currency_code: "zh-XC" },
  { name: "SRI LANKA", currency_name: "LKR", currency_code: "en-IN" },
  { name: "SUDAN (THE)", currency_name: "SDG", currency_code: "en-US" },
  { name: "SURINAME", currency_name: "SRD", currency_code: "fr-XC" },
  {
    name: "SVALBARD AND JAN MAYEN",
    currency_name: "NOK",
    currency_code: "es-XC",
  },
  { name: "SWAZILAND", currency_name: "SZL", currency_code: "zh-XC" },
  { name: "SWEDEN", currency_name: "SEK", currency_code: "da-DK" },
  { name: "SWITZERLAND", currency_name: "CHE", currency_code: "en-US" },
  { name: "SWITZERLAND", currency_name: "CHF", currency_code: "fr-XC" },
  { name: "SWITZERLAND", currency_name: "CHW", currency_code: "es-XC" },
  {
    name: "SYRIAN ARAB REPUBLIC",
    currency_name: "SYP",
    currency_code: "zh-XC",
  },
  {
    name: "TAIWAN (PROVINCE OF CHINA)",
    currency_name: "TWD",
    currency_code: "en-US",
  },
  { name: "TAJIKISTAN", currency_name: "TJS", currency_code: "fr-XC" },
  {
    name: "TANZANIA, UNITED REPUBLIC OF",
    currency_name: "TZS",
    currency_code: "es-XC",
  },
  { name: "THAILAND", currency_name: "THB", currency_code: "zh-XC" },
  { name: "TIMOR-LESTE", currency_name: "USD", currency_code: "en-US" },
  { name: "TOGO", currency_name: "XOF", currency_code: "fr-XC" },
  { name: "TOKELAU", currency_name: "NZD", currency_code: "es-XC" },
  { name: "TONGA", currency_name: "TOP", currency_code: "zh-XC" },
  { name: "TRINIDAD AND TOBAGO", currency_name: "TTD", currency_code: "es-XC" },
  { name: "TUNISIA", currency_name: "TND", currency_code: "en-US" },
  { name: "TURKEY", currency_name: "TRY", currency_code: "fr-XC" },
  { name: "TURKMENISTAN", currency_name: "TMT", currency_code: "zh-XC" },
  {
    name: "TURKS AND CAICOS ISLANDS",
    currency_name: "USD",
    currency_code: "fr-XC",
  },
  { name: "TUVALU", currency_name: "AUD", currency_code: "en-US" },
  { name: "UGANDA", currency_name: "UGX", currency_code: "es-XC" },
  { name: "UKRAINE", currency_name: "UAH", currency_code: "zh-XC" },
  {
    name: "UNITED ARAB EMIRATES",
    currency_name: "AED",
    currency_code: "en-US",
  },
  {
    name: "UNITED KINGDOM",
    currency_name: "GBP",
    currency_code: "en-GB",
  },
  {
    name: "UNITED STATES MINOR OUTLYING ISLANDS (THE)",
    currency_name: "USD",
    currency_code: "es-XC",
  },
  {
    name: "UNITED STATES",
    currency_name: "USD",
    currency_code: "en-US",
  },
  { name: "URUGUAY", currency_name: "UYI", currency_code: "fr-XC" },
  { name: "URUGUAY", currency_name: "UYU", currency_code: "es-XC" },
  { name: "UZBEKISTAN", currency_name: "UZS", currency_code: "zh-XC" },
  { name: "VANUATU", currency_name: "VUV", currency_code: "es-XC" },
  {
    name: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    currency_name: "VEF",
    currency_code: "en-US",
  },
  {
    name: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    currency_name: "VED",
    currency_code: "fr-XC",
  },
  { name: "VIET NAM", currency_name: "VND", currency_code: "zh-XC" },
  {
    name: "VIRGIN ISLANDS (BRITISH)",
    currency_name: "USD",
    currency_code: "en-GB",
  },
  {
    name: "VIRGIN ISLANDS (U.S.)",
    currency_name: "USD",
    currency_code: "zh-HK",
  },
  { name: "WALLIS AND FUTUNA", currency_name: "XPF", currency_code: "hu-HU" },
  { name: "WESTERN SAHARA", currency_name: "MAD", currency_code: "en-US" },
  { name: "YEMEN", currency_name: "YER", currency_code: "fr-XC" },
  { name: "ZAMBIA", currency_name: "ZMW", currency_code: "es-XC" },
  { name: "ZIMBABWE", currency_name: "ZWL", currency_code: "zh-XC" },
  { name: "ÅLAND ISLANDS", currency_name: "EUR", currency_code: "en-US" },
];

export default CURRENCY_CODES;
