const PPP_INFO = {
  page: 1,
  pages: 1,
  per_page: 20000,
  total: 3724,
  sourceid: "2",
  lastupdated: "2024-09-19",
};
const PPP_DATA = [
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AF",
      value: "Afghanistan",
    },
    countryiso3code: "AFG",
    date: "2022",
    value: 14.9102820470681,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AL",
      value: "Albania",
    },
    countryiso3code: "ALB",
    date: "2023",
    value: 39.3625610746,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "DZ",
      value: "Algeria",
    },
    countryiso3code: "DZA",
    date: "2023",
    value: 41.966491662277,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AD",
      value: "Andorra",
    },
    countryiso3code: "AND",
    date: "2023",
    value: 0.601311820072143,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AO",
      value: "Angola",
    },
    countryiso3code: "AGO",
    date: "2023",
    value: 209.922137539756,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AG",
      value: "Antigua and Barbuda",
    },
    countryiso3code: "ATG",
    date: "2023",
    value: 1.83044748608644,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AR",
      value: "Argentina",
    },
    countryiso3code: "ARG",
    date: "2023",
    value: 138.535504351528,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AM",
      value: "Armenia",
    },
    countryiso3code: "ARM",
    date: "2023",
    value: 148.376614712426,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AW",
      value: "Aruba",
    },
    countryiso3code: "ABW",
    date: "2022",
    value: 1.3177220251751,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AU",
      value: "Australia",
    },
    countryiso3code: "AUS",
    date: "2023",
    value: 1.391128,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AT",
      value: "Austria",
    },
    countryiso3code: "AUT",
    date: "2023",
    value: 0.708583,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AZ",
      value: "Azerbaijan",
    },
    countryiso3code: "AZE",
    date: "2023",
    value: 0.513547203253494,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BS",
      value: "Bahamas, The",
    },
    countryiso3code: "BHS",
    date: "2023",
    value: 0.977354359953442,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BH",
      value: "Bahrain",
    },
    countryiso3code: "BHR",
    date: "2023",
    value: 0.171277544238009,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BD",
      value: "Bangladesh",
    },
    countryiso3code: "BGD",
    date: "2023",
    value: 28.6414527647285,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BB",
      value: "Barbados",
    },
    countryiso3code: "BRB",
    date: "2023",
    value: 2.34255483499186,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BY",
      value: "Belarus",
    },
    countryiso3code: "BLR",
    date: "2023",
    value: 0.765644162330282,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BE",
      value: "Belgium",
    },
    countryiso3code: "BEL",
    date: "2023",
    value: 0.701943,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BZ",
      value: "Belize",
    },
    countryiso3code: "BLZ",
    date: "2023",
    value: 1.12538351296439,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BJ",
      value: "Benin",
    },
    countryiso3code: "BEN",
    date: "2023",
    value: 204.868568650122,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BM",
      value: "Bermuda",
    },
    countryiso3code: "BMU",
    date: "2022",
    value: 1.15182313324744,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BT",
      value: "Bhutan",
    },
    countryiso3code: "BTN",
    date: "2022",
    value: 19.3820884877905,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BO",
      value: "Bolivia",
    },
    countryiso3code: "BOL",
    date: "2023",
    value: 2.38405548204567,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BA",
      value: "Bosnia and Herzegovina",
    },
    countryiso3code: "BIH",
    date: "2023",
    value: 0.66728664015,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BW",
      value: "Botswana",
    },
    countryiso3code: "BWA",
    date: "2023",
    value: 5.08539302521326,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BR",
      value: "Brazil",
    },
    countryiso3code: "BRA",
    date: "2023",
    value: 2.43687587390419,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "VG",
      value: "British Virgin Islands",
    },
    countryiso3code: "VGB",
    date: "2017",
    value: 1.02022969722748,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BN",
      value: "Brunei Darussalam",
    },
    countryiso3code: "BRN",
    date: "2023",
    value: 0.519406037460836,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BG",
      value: "Bulgaria",
    },
    countryiso3code: "BGR",
    date: "2023",
    value: 0.73855396687,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BF",
      value: "Burkina Faso",
    },
    countryiso3code: "BFA",
    date: "2023",
    value: 194.43591626971,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "BI",
      value: "Burundi",
    },
    countryiso3code: "BDI",
    date: "2023",
    value: 724.166952175717,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CV",
      value: "Cabo Verde",
    },
    countryiso3code: "CPV",
    date: "2023",
    value: 48.4973794995055,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KH",
      value: "Cambodia",
    },
    countryiso3code: "KHM",
    date: "2023",
    value: 1370.47995628293,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CM",
      value: "Cameroon",
    },
    countryiso3code: "CMR",
    date: "2023",
    value: 188.690484605277,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CA",
      value: "Canada",
    },
    countryiso3code: "CAN",
    date: "2023",
    value: 1.169928,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KY",
      value: "Cayman Islands",
    },
    countryiso3code: "CYM",
    date: "2022",
    value: 0.940041537680288,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CF",
      value: "Central African Republic",
    },
    countryiso3code: "CAF",
    date: "2023",
    value: 238.889655747751,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TD",
      value: "Chad",
    },
    countryiso3code: "TCD",
    date: "2023",
    value: 221.579449198094,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CL",
      value: "Chile",
    },
    countryiso3code: "CHL",
    date: "2023",
    value: 431.415905,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CN",
      value: "China",
    },
    countryiso3code: "CHN",
    date: "2023",
    value: 3.63870415348481,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CO",
      value: "Colombia",
    },
    countryiso3code: "COL",
    date: "2023",
    value: 1401.241791,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KM",
      value: "Comoros",
    },
    countryiso3code: "COM",
    date: "2023",
    value: 187.337048545402,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CD",
      value: "Congo, Dem. Rep.",
    },
    countryiso3code: "COD",
    date: "2023",
    value: 949.600728138881,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CG",
      value: "Congo, Rep.",
    },
    countryiso3code: "COG",
    date: "2023",
    value: 219.499486949798,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CR",
      value: "Costa Rica",
    },
    countryiso3code: "CRI",
    date: "2023",
    value: 323.002654,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CI",
      value: "Cote d'Ivoire",
    },
    countryiso3code: "CIV",
    date: "2023",
    value: 212.455422789034,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "HR",
      value: "Croatia",
    },
    countryiso3code: "HRV",
    date: "2023",
    value: 0.432290262501,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CU",
      value: "Cuba",
    },
    countryiso3code: "CUB",
    date: "2011",
    value: 0.321938711455632,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CW",
      value: "Curacao",
    },
    countryiso3code: "CUW",
    date: "2022",
    value: 1.24247153090058,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CY",
      value: "Cyprus",
    },
    countryiso3code: "CYP",
    date: "2023",
    value: 0.562049096539,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CZ",
      value: "Czechia",
    },
    countryiso3code: "CZE",
    date: "2023",
    value: 12.55055,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "DK",
      value: "Denmark",
    },
    countryiso3code: "DNK",
    date: "2023",
    value: 6.106244,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "DJ",
      value: "Djibouti",
    },
    countryiso3code: "DJI",
    date: "2023",
    value: 88.9688656185565,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "DM",
      value: "Dominica",
    },
    countryiso3code: "DMA",
    date: "2023",
    value: 1.37371497415892,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "DO",
      value: "Dominican Republic",
    },
    countryiso3code: "DOM",
    date: "2023",
    value: 23.4976010939251,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "EC",
      value: "Ecuador",
    },
    countryiso3code: "ECU",
    date: "2023",
    value: 0.411672575202021,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "EG",
      value: "Egypt, Arab Rep.",
    },
    countryiso3code: "EGY",
    date: "2023",
    value: 4.78817690627537,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SV",
      value: "El Salvador",
    },
    countryiso3code: "SLV",
    date: "2023",
    value: 0.426094939009153,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GQ",
      value: "Equatorial Guinea",
    },
    countryiso3code: "GNQ",
    date: "2023",
    value: 228.929537109749,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ER",
      value: "Eritrea",
    },
    countryiso3code: "ERI",
    date: "2021",
    value: 4.93847894668579,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "EE",
      value: "Estonia",
    },
    countryiso3code: "EST",
    date: "2023",
    value: 0.562992,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SZ",
      value: "Eswatini",
    },
    countryiso3code: "SWZ",
    date: "2023",
    value: 5.96839720517122,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ET",
      value: "Ethiopia",
    },
    countryiso3code: "ETH",
    date: "2023",
    value: 22.171172211744,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "FO",
      value: "Faroe Islands",
    },
    countryiso3code: "FRO",
    date: "2022",
    value: 6.1901196523216,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "FJ",
      value: "Fiji",
    },
    countryiso3code: "FJI",
    date: "2023",
    value: 0.877554298905316,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "FI",
      value: "Finland",
    },
    countryiso3code: "FIN",
    date: "2023",
    value: 0.764142,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "FR",
      value: "France",
    },
    countryiso3code: "FRA",
    date: "2023",
    value: 0.672356,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GA",
      value: "Gabon",
    },
    countryiso3code: "GAB",
    date: "2023",
    value: 232.714326775648,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GM",
      value: "Gambia, The",
    },
    countryiso3code: "GMB",
    date: "2023",
    value: 16.3016525087778,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GE",
      value: "Georgia",
    },
    countryiso3code: "GEO",
    date: "2023",
    value: 0.864621897098242,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "DE",
      value: "Germany",
    },
    countryiso3code: "DEU",
    date: "2023",
    value: 0.703527,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GH",
      value: "Ghana",
    },
    countryiso3code: "GHA",
    date: "2023",
    value: 3.30353646845364,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GR",
      value: "Greece",
    },
    countryiso3code: "GRC",
    date: "2023",
    value: 0.516235,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GL",
      value: "Greenland",
    },
    countryiso3code: "GRL",
    date: "2021",
    value: 5.2741265296936,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GD",
      value: "Grenada",
    },
    countryiso3code: "GRD",
    date: "2023",
    value: 1.60029951889601,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GT",
      value: "Guatemala",
    },
    countryiso3code: "GTM",
    date: "2023",
    value: 3.22796367830501,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GN",
      value: "Guinea",
    },
    countryiso3code: "GIN",
    date: "2023",
    value: 3339.63879870911,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GW",
      value: "Guinea-Bissau",
    },
    countryiso3code: "GNB",
    date: "2023",
    value: 210.840293617353,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GY",
      value: "Guyana",
    },
    countryiso3code: "GUY",
    date: "2023",
    value: 77.8205942538508,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "HT",
      value: "Haiti",
    },
    countryiso3code: "HTI",
    date: "2023",
    value: 73.3113538690668,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "HN",
      value: "Honduras",
    },
    countryiso3code: "HND",
    date: "2023",
    value: 11.0790007804808,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "HK",
      value: "Hong Kong SAR, China",
    },
    countryiso3code: "HKG",
    date: "2023",
    value: 5.55294423577267,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "HU",
      value: "Hungary",
    },
    countryiso3code: "HUN",
    date: "2023",
    value: 170.212279,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "IS",
      value: "Iceland",
    },
    countryiso3code: "ISL",
    date: "2023",
    value: 140.155004,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "IN",
      value: "India",
    },
    countryiso3code: "IND",
    date: "2023",
    value: 20.2166267502145,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ID",
      value: "Indonesia",
    },
    countryiso3code: "IDN",
    date: "2023",
    value: 4821.59457441777,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "IR",
      value: "Iran, Islamic Rep.",
    },
    countryiso3code: "IRN",
    date: "2023",
    value: 91081.211147176,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "IQ",
      value: "Iraq",
    },
    countryiso3code: "IRQ",
    date: "2023",
    value: 519.239819509762,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "IE",
      value: "Ireland",
    },
    countryiso3code: "IRL",
    date: "2023",
    value: 0.751366,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "IL",
      value: "Israel",
    },
    countryiso3code: "ISR",
    date: "2023",
    value: 3.586914,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "IT",
      value: "Italy",
    },
    countryiso3code: "ITA",
    date: "2023",
    value: 0.604018,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "JM",
      value: "Jamaica",
    },
    countryiso3code: "JAM",
    date: "2023",
    value: 92.3501422303604,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "JP",
      value: "Japan",
    },
    countryiso3code: "JPN",
    date: "2023",
    value: 94.677395,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "JO",
      value: "Jordan",
    },
    countryiso3code: "JOR",
    date: "2023",
    value: 0.304468780401446,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KZ",
      value: "Kazakhstan",
    },
    countryiso3code: "KAZ",
    date: "2023",
    value: 152.354214889111,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KE",
      value: "Kenya",
    },
    countryiso3code: "KEN",
    date: "2023",
    value: 43.1224591723171,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KI",
      value: "Kiribati",
    },
    countryiso3code: "KIR",
    date: "2023",
    value: 0.893225826763546,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KR",
      value: "Korea, Rep.",
    },
    countryiso3code: "KOR",
    date: "2023",
    value: 800.348017,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "XK",
      value: "Kosovo",
    },
    countryiso3code: "XKX",
    date: "2023",
    value: 0.365662394514768,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KW",
      value: "Kuwait",
    },
    countryiso3code: "KWT",
    date: "2023",
    value: 0.204475956836398,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KG",
      value: "Kyrgyz Republic",
    },
    countryiso3code: "KGZ",
    date: "2023",
    value: 24.3658326983705,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LA",
      value: "Lao PDR",
    },
    countryiso3code: "LAO",
    date: "2023",
    value: 3936.35447275292,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LV",
      value: "Latvia",
    },
    countryiso3code: "LVA",
    date: "2023",
    value: 0.5045,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LB",
      value: "Lebanon",
    },
    countryiso3code: "LBN",
    date: "2022",
    value: 8125.00103496882,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LS",
      value: "Lesotho",
    },
    countryiso3code: "LSO",
    date: "2023",
    value: 5.79823538516503,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LR",
      value: "Liberia",
    },
    countryiso3code: "LBR",
    date: "2023",
    value: 0.439516464456266,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LY",
      value: "Libya",
    },
    countryiso3code: "LBY",
    date: "2023",
    value: 1.7961438286171,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LT",
      value: "Lithuania",
    },
    countryiso3code: "LTU",
    date: "2023",
    value: 0.483176,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LU",
      value: "Luxembourg",
    },
    countryiso3code: "LUX",
    date: "2023",
    value: 0.82753,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MO",
      value: "Macao SAR, China",
    },
    countryiso3code: "MAC",
    date: "2023",
    value: 4.76146075882428,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MG",
      value: "Madagascar",
    },
    countryiso3code: "MDG",
    date: "2023",
    value: 1248.82974959173,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MW",
      value: "Malawi",
    },
    countryiso3code: "MWI",
    date: "2023",
    value: 418.309235434928,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MY",
      value: "Malaysia",
    },
    countryiso3code: "MYS",
    date: "2023",
    value: 1.42626807760626,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MV",
      value: "Maldives",
    },
    countryiso3code: "MDV",
    date: "2023",
    value: 7.85656491962535,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ML",
      value: "Mali",
    },
    countryiso3code: "MLI",
    date: "2023",
    value: 199.69700312756,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MT",
      value: "Malta",
    },
    countryiso3code: "MLT",
    date: "2023",
    value: 0.561048150939,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MH",
      value: "Marshall Islands",
    },
    countryiso3code: "MHL",
    date: "2023",
    value: 0.902709949689365,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MR",
      value: "Mauritania",
    },
    countryiso3code: "MRT",
    date: "2023",
    value: 11.3448806661197,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MU",
      value: "Mauritius",
    },
    countryiso3code: "MUS",
    date: "2023",
    value: 17.5198752901718,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MX",
      value: "Mexico",
    },
    countryiso3code: "MEX",
    date: "2023",
    value: 9.65993,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "FM",
      value: "Micronesia, Fed. Sts.",
    },
    countryiso3code: "FSM",
    date: "2023",
    value: 0.946808218876195,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MD",
      value: "Moldova",
    },
    countryiso3code: "MDA",
    date: "2023",
    value: 6.94888047523769,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MN",
      value: "Mongolia",
    },
    countryiso3code: "MNG",
    date: "2023",
    value: 1103.340170893,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ME",
      value: "Montenegro",
    },
    countryiso3code: "MNE",
    date: "2023",
    value: 0.355971914047,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MA",
      value: "Morocco",
    },
    countryiso3code: "MAR",
    date: "2023",
    value: 3.81892783199548,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MZ",
      value: "Mozambique",
    },
    countryiso3code: "MOZ",
    date: "2023",
    value: 23.4570282308295,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MM",
      value: "Myanmar",
    },
    countryiso3code: "MMR",
    date: "2023",
    value: 422.318062837737,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "NA",
      value: "Namibia",
    },
    countryiso3code: "NAM",
    date: "2023",
    value: 6.85819521829883,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "NR",
      value: "Nauru",
    },
    countryiso3code: "NRU",
    date: "2023",
    value: 1.41419412769361,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "NP",
      value: "Nepal",
    },
    countryiso3code: "NPL",
    date: "2023",
    value: 33.4071598443357,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "NL",
      value: "Netherlands",
    },
    countryiso3code: "NLD",
    date: "2023",
    value: 0.739454,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "NZ",
      value: "New Zealand",
    },
    countryiso3code: "NZL",
    date: "2023",
    value: 1.460444,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "NI",
      value: "Nicaragua",
    },
    countryiso3code: "NIC",
    date: "2023",
    value: 11.4631845494296,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "NE",
      value: "Niger",
    },
    countryiso3code: "NER",
    date: "2023",
    value: 206.364660706062,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "NG",
      value: "Nigeria",
    },
    countryiso3code: "NGA",
    date: "2023",
    value: 165.785284949663,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "MK",
      value: "North Macedonia",
    },
    countryiso3code: "MKD",
    date: "2023",
    value: 18.6516828695,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "NO",
      value: "Norway",
    },
    countryiso3code: "NOR",
    date: "2023",
    value: 8.894996,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "OM",
      value: "Oman",
    },
    countryiso3code: "OMN",
    date: "2023",
    value: 0.201639189861095,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PK",
      value: "Pakistan",
    },
    countryiso3code: "PAK",
    date: "2023",
    value: 56.2744628403118,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PW",
      value: "Palau",
    },
    countryiso3code: "PLW",
    date: "2023",
    value: 0.832744639508332,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PA",
      value: "Panama",
    },
    countryiso3code: "PAN",
    date: "2023",
    value: 0.470127945537058,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PG",
      value: "Papua New Guinea",
    },
    countryiso3code: "PNG",
    date: "2023",
    value: 2.33960072399207,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PY",
      value: "Paraguay",
    },
    countryiso3code: "PRY",
    date: "2023",
    value: 2612.61995392143,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PE",
      value: "Peru",
    },
    countryiso3code: "PER",
    date: "2023",
    value: 1.74452671883385,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PH",
      value: "Philippines",
    },
    countryiso3code: "PHL",
    date: "2023",
    value: 19.2695632962606,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PL",
      value: "Poland",
    },
    countryiso3code: "POL",
    date: "2023",
    value: 1.879248,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PT",
      value: "Portugal",
    },
    countryiso3code: "PRT",
    date: "2023",
    value: 0.517344,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PR",
      value: "Puerto Rico",
    },
    countryiso3code: "PRI",
    date: "2023",
    value: 0.771056552808603,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "QA",
      value: "Qatar",
    },
    countryiso3code: "QAT",
    date: "2022",
    value: 2.62893384958065,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "RO",
      value: "Romania",
    },
    countryiso3code: "ROU",
    date: "2023",
    value: 1.75887412014,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "RU",
      value: "Russian Federation",
    },
    countryiso3code: "RUS",
    date: "2023",
    value: 26.6801077041224,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "RW",
      value: "Rwanda",
    },
    countryiso3code: "RWA",
    date: "2023",
    value: 345.229437397842,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "WS",
      value: "Samoa",
    },
    countryiso3code: "WSM",
    date: "2023",
    value: 1.69170325252631,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SM",
      value: "San Marino",
    },
    countryiso3code: "SMR",
    date: "2021",
    value: 0.707382142543793,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ST",
      value: "Sao Tome and Principe",
    },
    countryiso3code: "STP",
    date: "2023",
    value: 9.79520128561749,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SA",
      value: "Saudi Arabia",
    },
    countryiso3code: "SAU",
    date: "2023",
    value: 1.97040765961378,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SN",
      value: "Senegal",
    },
    countryiso3code: "SEN",
    date: "2023",
    value: 219.128224654895,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "RS",
      value: "Serbia",
    },
    countryiso3code: "SRB",
    date: "2023",
    value: 44.9444593312,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SC",
      value: "Seychelles",
    },
    countryiso3code: "SYC",
    date: "2023",
    value: 7.6661137781464,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SL",
      value: "Sierra Leone",
    },
    countryiso3code: "SLE",
    date: "2023",
    value: 4.99976356177989,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SG",
      value: "Singapore",
    },
    countryiso3code: "SGP",
    date: "2023",
    value: 0.804086116592075,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SX",
      value: "Sint Maarten (Dutch part)",
    },
    countryiso3code: "SXM",
    date: "2023",
    value: 1.36985036088976,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SK",
      value: "Slovak Republic",
    },
    countryiso3code: "SVK",
    date: "2023",
    value: 0.506852,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SI",
      value: "Slovenia",
    },
    countryiso3code: "SVN",
    date: "2023",
    value: 0.541355,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SB",
      value: "Solomon Islands",
    },
    countryiso3code: "SLB",
    date: "2023",
    value: 6.08033727731148,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SO",
      value: "Somalia",
    },
    countryiso3code: "SOM",
    date: "2023",
    value: 10867.5164798451,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ZA",
      value: "South Africa",
    },
    countryiso3code: "ZAF",
    date: "2023",
    value: 7.2801946616266,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SS",
      value: "South Sudan",
    },
    countryiso3code: "SSD",
    date: "2015",
    value: 3.37095053486236,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ES",
      value: "Spain",
    },
    countryiso3code: "ESP",
    date: "2023",
    value: 0.572592,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LK",
      value: "Sri Lanka",
    },
    countryiso3code: "LKA",
    date: "2023",
    value: 86.7353177891082,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "KN",
      value: "St. Kitts and Nevis",
    },
    countryiso3code: "KNA",
    date: "2023",
    value: 1.82301713051001,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "LC",
      value: "St. Lucia",
    },
    countryiso3code: "LCA",
    date: "2023",
    value: 1.50211728050232,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "VC",
      value: "St. Vincent and the Grenadines",
    },
    countryiso3code: "VCT",
    date: "2023",
    value: 1.39641113345768,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SD",
      value: "Sudan",
    },
    countryiso3code: "SDN",
    date: "2023",
    value: 514.307134863817,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SR",
      value: "Suriname",
    },
    countryiso3code: "SUR",
    date: "2023",
    value: 10.6044507958133,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SE",
      value: "Sweden",
    },
    countryiso3code: "SWE",
    date: "2023",
    value: 8.509281,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "CH",
      value: "Switzerland",
    },
    countryiso3code: "CHE",
    date: "2023",
    value: 0.966273,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "SY",
      value: "Syrian Arab Republic",
    },
    countryiso3code: "SYR",
    date: "2021",
    value: 417.322418212891,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TJ",
      value: "Tajikistan",
    },
    countryiso3code: "TJK",
    date: "2023",
    value: 2.53711704890444,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TZ",
      value: "Tanzania",
    },
    countryiso3code: "TZA",
    date: "2023",
    value: 726.476102762249,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TH",
      value: "Thailand",
    },
    countryiso3code: "THA",
    date: "2023",
    value: 10.6559974609307,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TL",
      value: "Timor-Leste",
    },
    countryiso3code: "TLS",
    date: "2023",
    value: 0.322713344756041,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TG",
      value: "Togo",
    },
    countryiso3code: "TGO",
    date: "2023",
    value: 194.731218631422,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TO",
      value: "Tonga",
    },
    countryiso3code: "TON",
    date: "2022",
    value: 1.51582880307416,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TT",
      value: "Trinidad and Tobago",
    },
    countryiso3code: "TTO",
    date: "2023",
    value: 3.91967295016779,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TN",
      value: "Tunisia",
    },
    countryiso3code: "TUN",
    date: "2023",
    value: 0.884587105183473,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TR",
      value: "Turkiye",
    },
    countryiso3code: "TUR",
    date: "2023",
    value: 6.974967,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TM",
      value: "Turkmenistan",
    },
    countryiso3code: "TKM",
    date: "2023",
    value: 1.43591360484589,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TC",
      value: "Turks and Caicos Islands",
    },
    countryiso3code: "TCA",
    date: "2023",
    value: 1.2263883735119,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "TV",
      value: "Tuvalu",
    },
    countryiso3code: "TUV",
    date: "2023",
    value: 1.42727299541079,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "UG",
      value: "Uganda",
    },
    countryiso3code: "UGA",
    date: "2023",
    value: 1228.430688278,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "UA",
      value: "Ukraine",
    },
    countryiso3code: "UKR",
    date: "2023",
    value: 10.5235219853264,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "AE",
      value: "United Arab Emirates",
    },
    countryiso3code: "ARE",
    date: "2023",
    value: 2.31884546890079,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "GB",
      value: "United Kingdom",
    },
    countryiso3code: "GBR",
    date: "2023",
    value: 0.667418,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "US",
      value: "United States",
    },
    countryiso3code: "USA",
    date: "2023",
    value: 1,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "UY",
      value: "Uruguay",
    },
    countryiso3code: "URY",
    date: "2023",
    value: 25.7177624165063,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "UZ",
      value: "Uzbekistan",
    },
    countryiso3code: "UZB",
    date: "2023",
    value: 3012.05243343799,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "VU",
      value: "Vanuatu",
    },
    countryiso3code: "VUT",
    date: "2023",
    value: 120.98165140284,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "VE",
      value: "Venezuela, RB",
    },
    countryiso3code: "VEN",
    date: "2011",
    value: 2.68098258972168,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "VN",
      value: "Viet Nam",
    },
    countryiso3code: "VNM",
    date: "2023",
    value: 6805.03072394812,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "VI",
      value: "Virgin Islands (U.S.)",
    },
    countryiso3code: "VIR",
    date: "2021",
    value: 0.907823741436005,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "PS",
      value: "West Bank and Gaza",
    },
    countryiso3code: "PSE",
    date: "2023",
    value: 0.571905822259302,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "YE",
      value: "Yemen, Rep.",
    },
    countryiso3code: "YEM",
    date: "2013",
    value: 93.6313171386719,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ZM",
      value: "Zambia",
    },
    countryiso3code: "ZMB",
    date: "2023",
    value: 6.70755666282946,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
  {
    indicator: {
      id: "PA.NUS.PPP",
      value: "PPP conversion factor, GDP (LCU per international $)",
    },
    country: {
      id: "ZW",
      value: "Zimbabwe",
    },
    countryiso3code: "ZWE",
    date: "2023",
    value: 1921.54418925218,
    unit: "",
    obs_status: "",
    decimal: 2,
  },
];

export default PPP_DATA;
