'use client';
import SEOHead from '../components/SEOHead';
import Breadcrumb from '../components/Breadcrumb';
import { Link } from '@/navigation';
import styles from './StaticDocPage.module.scss';
const disclaimerSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebPage',
  name: 'Financial Disclaimer — Rupee Calculator',
  url: 'https://rupees.vercel.app/disclaimer',
  description:
    'Financial disclaimer for Rupee Calculator. All tools are for educational purposes only and do not constitute investment advice.',
  breadcrumb: {
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://rupees.vercel.app/' },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Disclaimer',
        item: 'https://rupees.vercel.app/disclaimer',
      },
    ],
  },
};
const Disclaimer = () => {
  const lastUpdated = 'August 31, 2026';
  return (
    <main className={styles.container}>
      <SEOHead
        title="Financial Disclaimer — Rupee Calculator"
        description="Rupee Calculator is for educational purposes only. All projections are estimates based on inputs — not financial advice. Consult a SEBI-registered advisor."
        canonicalPath="/disclaimer"
        schema={disclaimerSchema}
        noIndex={false}
      />
      <Breadcrumb items={[{ name: 'Home', href: '/' }, { name: 'Disclaimer' }]} />
      <header className={styles.header}>
        <h1 className={styles.title}>Financial Disclaimer</h1>
        <p className={styles.dateSubtitle}>Last updated: {lastUpdated}</p>
      </header>
      <div className={styles.docBody}>
        {/* Key Disclaimer Box */}
        <div className={styles.calloutWarning}>
          <p className={styles.calloutTitle}>⚠️ Important: Educational Purpose Only</p>
          <p className={styles.calloutText}>
            All calculators, projections, and financial models on Rupee Calculator are provided
            solely for <strong>educational and informational purposes</strong>. They do not
            constitute financial, investment, tax, or legal advice. Past performance data does not
            guarantee future results.
          </p>
        </div>
        <section className={styles.section}>
          <h2 className={styles.sectionHeading}>1. No Investment Advice</h2>
          <p className={styles.paragraph}>
            Rupee Calculator is not a SEBI-registered investment advisor, research analyst, or
            financial planner. The tools provided — including SIP calculators, SWP retirement
            planners, EMI calculators, and mutual fund CAGR analysis — are mathematical modeling
            instruments only. They should not be used as the sole basis for any investment decision.
          </p>
          <p className={styles.paragraph}>
            Please consult a SEBI-registered investment advisor (RIA) or a qualified Certified
            Financial Planner (CFP) before making investment decisions based on any projections
            generated by our tools.
          </p>
        </section>
        <section className={styles.section}>
          <h2 className={styles.sectionHeading}>2. Forward-Looking Projections</h2>
          <p className={styles.paragraph}>
            Return projections generated by SIP, SWP, FD, and Mutual Fund calculators are based on
            user-specified expected return rates. Actual market returns may be significantly higher
            or lower. Equity mutual fund returns are subject to market risk, and unit NAVs can fall
            as well as rise.
          </p>
          <p className={styles.paragraph}>
            The phrase "historically, equity mutual funds have delivered 12-15% CAGR" refers to past
            multi-decade averages and does not imply or guarantee similar future returns.
          </p>
        </section>
        <section className={styles.section}>
          <h2 className={styles.sectionHeading}>3. Tax Information</h2>
          <p className={styles.paragraph}>
            Any tax-related information provided on this website (LTCG/STCG rates, Section 80C
            limits, TDS thresholds) reflects the tax laws as understood at the time of writing and
            is subject to change via Finance Acts and CBDT notifications. Always verify current tax
            rates with a qualified chartered accountant (CA) or tax advisor.
          </p>
        </section>
        <section className={styles.section}>
          <h2 className={styles.sectionHeading}>4. Data Accuracy</h2>
          <p className={styles.paragraph}>
            While we source data from official institutions (AMFI, World Bank, IMF), we make no
            warranty regarding the accuracy, completeness, or timeliness of any data displayed.
            Mutual fund NAVs shown reflect the latest available AMFI feed data, which may have a
            1-day lag. PPP and inflation data reflects the latest available World Bank and IMF
            publication cycles.
          </p>
        </section>
        <section className={styles.section}>
          <h2 className={styles.sectionHeading}>5. Mutual Fund Risk Disclosure</h2>
          <p className={styles.quoteBox}>
            "Mutual Fund investments are subject to market risks. Read all scheme related documents
            carefully before investing." — As mandated by SEBI (Securities and Exchange Board of
            India)
          </p>
        </section>
        <section className={styles.section}>
          <h2 className={styles.sectionHeading}>6. Limitation of Liability</h2>
          <p className={styles.paragraph}>
            Rupee Calculator and its creators shall not be held liable for any financial loss,
            investment decision, or action taken by any user based on the information, projections,
            or calculations provided on this website. Use of this website constitutes acceptance of
            these terms.
          </p>
        </section>
        <div className={styles.footerCenter}>
          <p className={styles.paragraph}>
            Have questions? Learn more on our{' '}
            <Link to="/about" className={styles.link}>
              About page
            </Link>{' '}
            or review our{' '}
            <Link to="/privacy" className={styles.link}>
              Privacy Policy
            </Link>
            .
          </p>
        </div>
      </div>
    </main>
  );
};
export default Disclaimer;
