import {
  compareTaxRegimes,
  getLatestRunningFinancialYear,
  TaxComparisonResult,
} from '../../utilities/incomeTaxCalculations';
import { Form16ExtractedData } from './types';
export function computeFileItrComparison(formData: Form16ExtractedData): TaxComparisonResult {
  return compareTaxRegimes({
    financialYear: getLatestRunningFinancialYear(),
    ageCategory: 'general',
    isSalaried: true,
    grossSalary: formData.grossSalary,
    basicSalary: formData.basicSalary,
    hraReceived: formData.hraReceived,
    rentPaid: formData.rentPaid,
    cityCategory: 'metro',
    professionalTax: formData.professionalTax,
    exemptAllowances: formData.exemptAllowances,
    customStandardDeduction: formData.standardDeduction,
    businessIncome: 0,
    isSelfOccupied: true,
    rentalIncome: 0,
    municipalTaxes: 0,
    homeLoanInterestProperty: 0,
    equityStcg: 0,
    equityLtcg: 0,
    otherCapitalGains: 0,
    savingsInterest: formData.section80Tta,
    fdInterest: 0,
    ppfInterest: 0,
    otherIncome: formData.otherIncome,
    section80C: formData.section80C,
    section80Ccd1b: formData.section80Ccd1b,
    section80Ccd2: 0,
    section80D_self: formData.section80D,
    selfSeniorCitizen: false,
    section80D_parents: 0,
    parentsSeniorCitizen: false,
    section80E: formData.section80E,
    section80G: formData.section80G,
    section80Tta: formData.section80Tta,
    otherDeductions: formData.otherDeductions,
  });
}
